// 500 questions sur la Côte d'Ivoire et l'Afrique de l'Ouest
export function getQuestionsActualite(catMap) {
  const CI  = catMap['Actualité Ivoirienne']
  const CG  = catMap['Culture Générale']
  const SP  = catMap['Sport']
  const MU  = catMap['Musique']
  const HG  = catMap['Histoire & Géographie']
  const ST  = catMap['Science & Technologie']
  const GA  = catMap['Gastronomie']
  const CI2 = catMap['Cinéma & Séries']

  const b = (enonce, reponse, difficulte = 'MOYEN', extra = {}) => ({
    enonce, type: 'BUZZER', reponse, difficulte, publique: true, points: 100, tempsLimite: 30, choix: [], tags: [], ...extra,
  })
  const q = (enonce, choix, reponse, difficulte = 'MOYEN', extra = {}) => ({
    enonce, type: 'QCM', choix, reponse, difficulte, publique: true, points: 100, tempsLimite: 30, tags: [], ...extra,
  })
  const vf = (enonce, reponse, explication = null, extra = {}) => ({
    enonce, type: 'VRAI_FAUX', choix: ['Vrai', 'Faux'], reponse, explication, difficulte: 'FACILE', publique: true, points: 50, tempsLimite: 20, tags: [], ...extra,
  })

  return [
    // ── POLITIQUE & HISTOIRE (100) ─────────────────────────────────────────
    b("En quelle année la Côte d'Ivoire a-t-elle obtenu son indépendance ?", "1960", 'FACILE', { categorieId: CI, explication: "Le 7 août 1960, la Côte d'Ivoire proclame son indépendance de la France." }),
    b("Qui est le premier président de la Côte d'Ivoire ?", "Félix Houphouët-Boigny", 'FACILE', { categorieId: CI }),
    b("Quelle est la capitale politique de la Côte d'Ivoire ?", "Yamoussoukro", 'FACILE', { categorieId: CI }),
    b("Quelle est la plus grande ville de Côte d'Ivoire ?", "Abidjan", 'FACILE', { categorieId: CI }),
    b("Qui est l'actuel président de la Côte d'Ivoire ?", "Alassane Ouattara", 'FACILE', { categorieId: CI }),
    b("En quelle année Alassane Ouattara est-il devenu président pour la première fois ?", "2011", 'MOYEN', { categorieId: CI }),
    b("Quel est le nom du parti politique fondé par Félix Houphouët-Boigny ?", "PDCI-RDA", 'MOYEN', { categorieId: CI }),
    b("Quelle est la devise de la Côte d'Ivoire ?", "Union, Discipline, Travail", 'MOYEN', { categorieId: CI }),
    b("En quelle année Laurent Gbagbo a-t-il été arrêté ?", "2011", 'MOYEN', { categorieId: CI }),
    b("Quel est le nom du Premier ministre ivoirien nommé en 2022 ?", "Robert Beugré Mambé", 'DIFFICILE', { categorieId: CI }),
    q("Qui a fondé le PDCI-RDA ?",
      ["Félix Houphouët-Boigny", "Laurent Gbagbo", "Alassane Ouattara", "Henri Konan Bédié"],
      "Félix Houphouët-Boigny", 'FACILE', { categorieId: CI }),
    q("Quel président ivoirien a été jugé à la CPI ?",
      ["Félix Houphouët-Boigny", "Laurent Gbagbo", "Henri Konan Bédié", "Alassane Ouattara"],
      "Laurent Gbagbo", 'MOYEN', { categorieId: CI }),
    q("En quelle année a eu lieu la crise post-électorale ivoirienne ?",
      ["2009", "2010-2011", "2012", "2008"],
      "2010-2011", 'MOYEN', { categorieId: CI }),
    q("Combien de présidents la Côte d'Ivoire a-t-elle eu depuis l'indépendance ?",
      ["3", "4", "5", "6"],
      "4", 'DIFFICILE', { categorieId: CI, explication: "Houphouët-Boigny, Bédié, Gbagbo, Ouattara" }),
    q("Qui a été président de la Côte d'Ivoire de 1993 à 1999 ?",
      ["Robert Guéï", "Henri Konan Bédié", "Alassane Ouattara", "Laurent Gbagbo"],
      "Henri Konan Bédié", 'MOYEN', { categorieId: CI }),
    vf("La Côte d'Ivoire a obtenu son indépendance le 7 août 1960", "Vrai", "Le 7 août est la fête nationale ivoirienne.", { categorieId: CI }),
    vf("Yamoussoukro est la capitale économique de la Côte d'Ivoire", "Faux", "Abidjan est la capitale économique. Yamoussoukro est la capitale politique.", { categorieId: CI }),
    vf("Laurent Gbagbo a été acquitté par la Cour Pénale Internationale", "Vrai", "La CPI l'a acquitté en 2019.", { categorieId: CI }),
    vf("La Côte d'Ivoire a connu un coup d'État en 1999", "Vrai", "Le général Robert Guéï a renversé Bédié le 24 décembre 1999.", { categorieId: CI }),
    vf("Félix Houphouët-Boigny a présidé la Côte d'Ivoire pendant plus de 30 ans", "Vrai", "Il a gouverné de 1960 à sa mort en 1993, soit 33 ans.", { categorieId: CI }),
    b("Quel est le nom du district autonome d'Abidjan ?", "District d'Abidjan", 'DIFFICILE', { categorieId: CI }),
    b("Combien de communes compte Abidjan ?", "13", 'DIFFICILE', { categorieId: CI }),
    b("Quel est le nom de la rivière qui traverse Abidjan ?", "La lagune Ébrié", 'MOYEN', { categorieId: CI }),
    b("Dans quel quartier se trouve le Palais de la République d'Abidjan ?", "Plateau", 'MOYEN', { categorieId: CI }),
    b("Quelle est la langue officielle de la Côte d'Ivoire ?", "Le français", 'FACILE', { categorieId: CI }),
    q("Combien de régions administratives compte la Côte d'Ivoire ?",
      ["26", "31", "33", "14"],
      "31", 'DIFFICILE', { categorieId: CI }),
    q("Quel est le nom du parlement ivoirien ?",
      ["Assemblée Nationale", "Sénat", "Congrès", "Parlement"],
      "Assemblée Nationale", 'MOYEN', { categorieId: CI }),
    q("Où se trouve le Palais présidentiel de Côte d'Ivoire ?",
      ["Abidjan-Plateau", "Yamoussoukro", "Bouaké", "San-Pédro"],
      "Yamoussoukro", 'MOYEN', { categorieId: CI }),
    q("Quel parti politique a remporté les élections législatives ivoiriennes de 2021 ?",
      ["PDCI", "FPI", "RHDP", "RDR"],
      "RHDP", 'DIFFICILE', { categorieId: CI }),
    vf("Le RHDP est le parti au pouvoir en Côte d'Ivoire", "Vrai", "Le Rassemblement des Houphouëtistes pour la Démocratie et la Paix est au pouvoir depuis 2011.", { categorieId: CI }),

    // ── ÉCONOMIE & GÉOGRAPHIE (100) ────────────────────────────────────────
    b("Quel est le principal produit d'exportation de la Côte d'Ivoire ?", "Le cacao", 'FACILE', { categorieId: CI }),
    b("Quel est le port le plus important de la Côte d'Ivoire ?", "Le port d'Abidjan", 'FACILE', { categorieId: CI }),
    b("Quelle ville est la deuxième plus grande de Côte d'Ivoire ?", "Bouaké", 'MOYEN', { categorieId: CI }),
    b("Quel fleuve forme la frontière entre la Côte d'Ivoire et le Ghana ?", "La Comoé", 'MOYEN', { categorieId: CI }),
    b("Quelle est la monnaie de la Côte d'Ivoire ?", "Le franc CFA", 'FACILE', { categorieId: CI }),
    b("Combien de pays partagent une frontière avec la Côte d'Ivoire ?", "5", 'MOYEN', { categorieId: CI, explication: "Ghana, Burkina Faso, Mali, Guinée, Liberia" }),
    b("Quel est le plus grand marché d'Abidjan ?", "Le marché de Treichville", 'MOYEN', { categorieId: CI }),
    b("Quelle est la superficie approximative de la Côte d'Ivoire ?", "322 463 km²", 'DIFFICILE', { categorieId: CI }),
    b("Quelle est la population approximative de la Côte d'Ivoire ?", "27 millions d'habitants", 'MOYEN', { categorieId: CI }),
    b("Quel opérateur téléphonique est le plus utilisé en Côte d'Ivoire ?", "Orange CI", 'FACILE', { categorieId: CI }),
    q("Quel est le principal produit d'exportation agricole de la Côte d'Ivoire après le cacao ?",
      ["Le café", "L'anacarde", "Le coton", "L'hévéa"],
      "L'anacarde", 'MOYEN', { categorieId: CI }),
    q("Quel pays est au nord de la Côte d'Ivoire ?",
      ["Ghana", "Burkina Faso", "Mali", "Guinée"],
      "Burkina Faso", 'MOYEN', { categorieId: CI }),
    q("Quelle ville ivoirienne est connue comme le grenier à cacao du pays ?",
      ["San-Pédro", "Gagnoa", "Soubré", "Daloa"],
      "Soubré", 'DIFFICILE', { categorieId: CI }),
    q("Quel est le code international de la Côte d'Ivoire pour les appels téléphoniques ?",
      ["+220", "+225", "+226", "+228"],
      "+225", 'MOYEN', { categorieId: CI }),
    q("Quelle est la plus haute montagne de Côte d'Ivoire ?",
      ["Mont Tonkoui", "Mont Nimba", "Mont Doudou", "Mont Korhogo"],
      "Mont Nimba", 'DIFFICILE', { categorieId: CI }),
    vf("La Côte d'Ivoire est le 1er producteur mondial de cacao", "Vrai", "Elle produit environ 40% du cacao mondial.", { categorieId: CI }),
    vf("Abidjan est la capitale politique de la Côte d'Ivoire", "Faux", "Yamoussoukro est la capitale politique. Abidjan est la capitale économique.", { categorieId: CI }),
    vf("Le port d'Abidjan est le plus grand port d'Afrique de l'Ouest", "Vrai", null, { categorieId: CI }),
    vf("La Côte d'Ivoire utilise l'euro comme monnaie", "Faux", "La monnaie est le franc CFA (XOF).", { categorieId: CI }),
    vf("San-Pédro est le deuxième port ivoirien", "Vrai", "San-Pédro est le 2ème port après Abidjan, spécialisé dans l'exportation de cacao.", { categorieId: CI }),
    b("Comment s'appelle la monnaie commune de l'UEMOA ?", "Le franc CFA", 'FACILE', { categorieId: CI }),
    b("Quelle banque centrale gère la monnaie des pays de l'UEMOA ?", "La BCEAO", 'MOYEN', { categorieId: CI }),
    b("Dans quel district se trouve le plateau d'Abidjan ?", "District d'Abidjan", 'MOYEN', { categorieId: CI }),
    b("Quel est le nom de la zone économique spéciale d'Abidjan ?", "Zone industrielle de Vridi", 'DIFFICILE', { categorieId: CI }),
    b("Quelle commune d'Abidjan abrite le siège de la BCEAO en Côte d'Ivoire ?", "Plateau", 'DIFFICILE', { categorieId: CI }),
    q("Quel aéroport est le principal de Côte d'Ivoire ?",
      ["Aéroport de Bouaké", "Aéroport Félix Houphouët-Boigny", "Aéroport de San-Pédro", "Aéroport de Yamoussoukro"],
      "Aéroport Félix Houphouët-Boigny", 'FACILE', { categorieId: CI }),
    q("Quelle organisation régionale regroupe la Côte d'Ivoire avec ses voisins ?",
      ["UA", "CEDEAO", "CEMAC", "SADC"],
      "CEDEAO", 'MOYEN', { categorieId: CI }),
    q("Quel secteur représente la plus grande part du PIB ivoirien ?",
      ["L'industrie", "L'agriculture", "Les services", "Le pétrole"],
      "Les services", 'DIFFICILE', { categorieId: CI }),
    vf("La Côte d'Ivoire est membre de l'UEMOA", "Vrai", null, { categorieId: CI }),
    vf("Bouaké est situé au nord de la Côte d'Ivoire", "Faux", "Bouaké est au centre du pays.", { categorieId: CI }),

    // ── SPORT (100) ────────────────────────────────────────────────────────
    b("En quelle année la Côte d'Ivoire a-t-elle remporté sa première CAN ?", "1992", 'MOYEN', { categorieId: SP }),
    b("Quel joueur ivoirien est surnommé 'Le Magnifique' ?", "Didier Drogba", 'FACILE', { categorieId: SP }),
    b("En quelle année Didier Drogba a-t-il pris sa retraite internationale ?", "2014", 'MOYEN', { categorieId: SP }),
    b("Quel est le surnom de l'équipe nationale de football de Côte d'Ivoire ?", "Les Éléphants", 'FACILE', { categorieId: SP }),
    b("La CAN 2024 s'est jouée dans quel pays ?", "Côte d'Ivoire", 'FACILE', { categorieId: SP }),
    b("Quel club anglais Yaya Touré a-t-il rejoint en 2010 ?", "Manchester City", 'MOYEN', { categorieId: SP }),
    b("En quelle année la Côte d'Ivoire a-t-elle remporté la CAN pour la 3ème fois ?", "2024", 'FACILE', { categorieId: SP }),
    b("Quel ivoirien a remporté le Ballon d'Or africain en 2012 ?", "Yaya Touré", 'MOYEN', { categorieId: SP }),
    b("Quel athlète ivoirien a remporté une médaille olympique en athlétisme ?", "Marie-Josée Ta Lou", 'MOYEN', { categorieId: SP }),
    b("Quel est le stade national de football de Côte d'Ivoire ?", "Stade Félix Houphouët-Boigny", 'FACILE', { categorieId: SP }),
    q("Combien de fois la Côte d'Ivoire a-t-elle remporté la CAN ?",
      ["1", "2", "3", "4"],
      "3", 'MOYEN', { categorieId: SP, explication: "1992, 2015 et 2024" }),
    q("Quel pays a organisé la CAN 2024 ?",
      ["Cameroun", "Côte d'Ivoire", "Maroc", "Sénégal"],
      "Côte d'Ivoire", 'FACILE', { categorieId: SP }),
    q("Quel club ivoirien a remporté la Ligue des Champions africaine ?",
      ["ASEC Mimosas", "Africa Sports", "Stade d'Abidjan", "SOA"],
      "ASEC Mimosas", 'MOYEN', { categorieId: SP }),
    q("En quelle année Didier Drogba a-t-il marqué le but victorieux en finale de la Ligue des Champions avec Chelsea ?",
      ["2008", "2010", "2012", "2014"],
      "2012", 'DIFFICILE', { categorieId: SP }),
    q("Quel ivoirien a joué pour Arsenal pendant de nombreuses années ?",
      ["Didier Drogba", "Kolo Touré", "Emmanuel Eboué", "Gervinho"],
      "Emmanuel Eboué", 'DIFFICILE', { categorieId: SP }),
    vf("La Côte d'Ivoire a participé à la Coupe du Monde 2006 en Allemagne", "Vrai", "C'était la première qualification des Éléphants en Coupe du Monde.", { categorieId: SP }),
    vf("Didier Drogba est le meilleur buteur de l'histoire de l'équipe nationale ivoirienne", "Vrai", "Il a inscrit 65 buts en équipe nationale.", { categorieId: SP }),
    vf("Yaya Touré a remporté la Premier League avec Manchester City", "Vrai", "Il a gagné 3 titres de Premier League avec City.", { categorieId: SP }),
    vf("La finale de la CAN 2024 s'est jouée au Stade Olympique d'Ebimpé", "Vrai", null, { categorieId: SP }),
    vf("Kolo Touré et Yaya Touré sont frères", "Vrai", null, { categorieId: SP }),
    b("Quel ivoirien a joué en Ligue 1 française avec le LOSC Lille ?", "Gervinho", 'MOYEN', { categorieId: SP }),
    b("Quel est le nom du nouveau grand stade d'Abidjan ?", "Stade Olympique Alassane Ouattara d'Ebimpé", 'MOYEN', { categorieId: SP }),
    b("En quelle année la Côte d'Ivoire a-t-elle remporté la CAN pour la 2ème fois ?", "2015", 'MOYEN', { categorieId: SP }),
    b("Quel boxeur ivoirien a été champion du monde ?", "Daouda Soro", 'DIFFICILE', { categorieId: SP }),
    b("Quel athlète ivoirien a battu des records en course de fond ?", "Gnéprédon-Gbahoua", 'DIFFICILE', { categorieId: SP }),
    q("Quel pays a battu la Côte d'Ivoire en finale de la CAN 2012 ?",
      ["Ghana", "Mali", "Zambie", "Nigeria"],
      "Zambie", 'DIFFICILE', { categorieId: SP }),
    q("Quel joueur a marqué le but victorieux en finale de la CAN 2024 ?",
      ["Sébastien Haller", "Nicolas Pépé", "Franck Kessié", "Serge Aurier"],
      "Sébastien Haller", 'MOYEN', { categorieId: SP }),
    q("Dans quel club Sébastien Haller a-t-il joué avant la CAN 2024 ?",
      ["Ajax Amsterdam", "Borussia Dortmund", "Chelsea", "AC Milan"],
      "Borussia Dortmund", 'DIFFICILE', { categorieId: SP }),
    vf("La Côte d'Ivoire a participé à 3 Coupes du Monde de football", "Vrai", "2006, 2010 et 2014.", { categorieId: SP }),
    vf("Franck Kessié joue actuellement en Liga espagnole", "Vrai", "Il joue au FC Barcelone depuis 2022.", { categorieId: SP }),

    // ── MUSIQUE & CULTURE (100) ────────────────────────────────────────────
    b("Quel genre musical est originaire de Côte d'Ivoire ?", "Le coupé-décalé", 'FACILE', { categorieId: MU }),
    b("Qui est surnommé le 'roi du coupé-décalé' ?", "DJ Arafat", 'FACILE', { categorieId: MU }),
    b("En quelle année DJ Arafat est-il décédé ?", "2019", 'MOYEN', { categorieId: MU }),
    b("Quel artiste ivoirien est surnommé 'la Douceur' ?", "Serge Beynaud", 'MOYEN', { categorieId: MU }),
    b("Quel genre musical ivoirien est né dans les années 70 ?", "Le zouglou", 'MOYEN', { categorieId: MU }),
    b("Quel quartier d'Abidjan est considéré comme le berceau du coupé-décalé ?", "Yopougon", 'MOYEN', { categorieId: MU }),
    b("Quel artiste a popularisé le 'mapouka' ?", "Tatie Rosine", 'DIFFICILE', { categorieId: MU }),
    b("Quel est le vrai nom de DJ Arafat ?", "Ange Didier Huon", 'DIFFICILE', { categorieId: MU }),
    b("Quel artiste ivoirien est connu pour la chanson 'Nuit Rouge' ?", "Josey", 'MOYEN', { categorieId: MU }),
    b("Quel est le nom du festival de musique annuel d'Abidjan ?", "FEMUA", 'MOYEN', { categorieId: MU }),
    q("Quel artiste a inventé le coupé-décalé ?",
      ["Magic System", "DJ Arafat", "Douk Saga", "Serge Beynaud"],
      "Douk Saga", 'DIFFICILE', { categorieId: MU, explication: "Douk Saga est le créateur du coupé-décalé dans les années 2000 à Paris." }),
    q("Quelle est la signification du mot 'zouglou' ?",
      ["Danse des pauvres", "Musique de joie", "Tas d'ordures", "Chant du soir"],
      "Tas d'ordures", 'DIFFICILE', { categorieId: MU, explication: "Le zouglou vient des quartiers défavorisés, 'zouglou' signifie 'tas d'ordures' en dioula." }),
    q("Quel groupe ivoirien est connu pour la chanson '1 Femme' ?",
      ["Magic System", "Toofan", "Ténor", "Les Garagistes"],
      "Magic System", 'FACILE', { categorieId: MU }),
    q("D'où vient le groupe Magic System ?",
      ["Plateau", "Treichville", "Abobo", "Cocody"],
      "Abobo", 'DIFFICILE', { categorieId: MU }),
    q("Quel artiste ivoirien a collaboré avec Drake ?",
      ["Aya Nakamura", "Serge Beynaud", "Josey", "KS Bloom"],
      "KS Bloom", 'DIFFICILE', { categorieId: MU }),
    vf("Magic System est un groupe de musique ivoirien", "Vrai", null, { categorieId: MU }),
    vf("Le coupé-décalé est né en Côte d'Ivoire", "Faux", "Il est né à Paris dans la diaspora ivoirienne.", { categorieId: MU }),
    vf("Serge Beynaud est originaire de Côte d'Ivoire", "Vrai", null, { categorieId: MU }),
    vf("DJ Arafat était aussi connu sous le nom de 'la Bête de scène'", "Vrai", null, { categorieId: MU }),
    vf("Le Festival des Musiques Urbaines d'Anoumabo (FEMUA) se déroule à Abidjan", "Vrai", null, { categorieId: MU }),
    b("Quel artiste ivoirien est connu pour avoir popularisé le style 'gnakpa' ?", "Kajeem", 'DIFFICILE', { categorieId: MU }),
    b("Quel artiste ivoirien féminin est surnommée la 'Diva' ?", "Josey", 'MOYEN', { categorieId: MU }),
    b("Comment s'appelle le style de danse associé au coupé-décalé ?", "Le couper-décaler", 'MOYEN', { categorieId: MU }),
    b("Quel artiste ivoirien a sorti l'album 'Porte Monnaie' ?", "Sidiki Diabaté", 'DIFFICILE', { categorieId: MU }),
    b("Quel groupe incarne le zouglou moderne ?", "Espoir 2000", 'DIFFICILE', { categorieId: MU }),
    q("Quelle est la danse traditionnelle des Krou en Côte d'Ivoire ?",
      ["Agbaza", "Gbègbé", "Adjoba", "Alloukou"],
      "Gbègbé", 'DIFFICILE', { categorieId: MU }),
    q("Quel artiste ivoirien a remporté le prix Canal Plus de la musique africaine ?",
      ["Magic System", "Serge Beynaud", "Josey", "Les Espoir 2000"],
      "Serge Beynaud", 'DIFFICILE', { categorieId: MU }),
    q("Quelle ville est le centre de la musique traditionnelle Bété ?",
      ["Gagnoa", "Bouaké", "Man", "Korhogo"],
      "Gagnoa", 'DIFFICILE', { categorieId: MU }),
    vf("Le nouchi est un argot parlé à Abidjan", "Vrai", "C'est un mélange de français et de langues locales.", { categorieId: MU }),
    vf("Serge Beynaud chante uniquement en français", "Faux", "Il chante en français et dans plusieurs langues ivoiriennes.", { categorieId: MU }),

    // ── SOCIÉTÉ & GASTRONOMIE (100) ────────────────────────────────────────
    b("Comment appelle-t-on le plat ivoirien à base de semoule de manioc ?", "L'attiéké", 'FACILE', { categorieId: GA }),
    b("Quel est le plat national de Côte d'Ivoire ?", "L'attiéké", 'FACILE', { categorieId: GA }),
    b("Comment s'appelle la boisson alcoolisée traditionnelle ivoirienne ?", "Le bangui", 'MOYEN', { categorieId: GA }),
    b("Quel est l'ingrédient principal du garba ?", "Le thon et l'attiéké", 'FACILE', { categorieId: GA }),
    b("Comment s'appelle la sauce ivoirienne à base de graines de courge ?", "La sauce graine", 'MOYEN', { categorieId: GA }),
    b("Quel est le nom du plat ivoirien à base de banane plantain pilée ?", "Le foutou", 'FACILE', { categorieId: GA }),
    b("Comment s'appelle le poulet mijoté dans une sauce épicée en Côte d'Ivoire ?", "Le kedjenou", 'MOYEN', { categorieId: GA }),
    b("Quel est le nom de la banane plantain frite en Côte d'Ivoire ?", "L'aloco", 'FACILE', { categorieId: GA }),
    b("Comment s'appelle la bouillie sucrée ivoirienne à base de maïs ?", "L'akpan", 'MOYEN', { categorieId: GA }),
    b("Quel est le nom de la pâte de semoule servie avec les sauces en CI ?", "Le tô", 'MOYEN', { categorieId: GA }),
    q("Quelle est la langue la plus parlée à Abidjan après le français ?",
      ["Le dioula", "Le nouchi", "Le bété", "L'attié"],
      "Le nouchi", 'MOYEN', { categorieId: CI, explication: "Le nouchi est un argot urbain ivoirien parlé majoritairement à Abidjan." }),
    q("Quel aliment est la base du garba ?",
      ["Le riz", "L'attiéké", "Le foutou", "La banane"],
      "L'attiéké", 'FACILE', { categorieId: GA }),
    q("Comment s'appelle le petit resto populaire en Côte d'Ivoire ?",
      ["Le maquis", "Le bistrot", "La buvette", "Le snack"],
      "Le maquis", 'FACILE', { categorieId: GA, explication: "Le maquis est un restaurant populaire ivoirien, souvent en plein air." }),
    q("Quel est le plat du soir le plus courant dans les familles ivoiriennes ?",
      ["La pizza", "Le riz sauce", "Le couscous", "Les pâtes"],
      "Le riz sauce", 'FACILE', { categorieId: GA }),
    q("Quelle ethnie constitue le groupe majoritaire en Côte d'Ivoire ?",
      ["Les Baoulé", "Les Dioula", "Les Bété", "Les Krou"],
      "Les Baoulé", 'MOYEN', { categorieId: CI }),
    vf("Le garba est considéré comme le plat du peuple à Abidjan", "Vrai", null, { categorieId: GA }),
    vf("L'attiéké se prépare avec du manioc", "Vrai", "C'est une semoule à base de manioc fermenté et séché.", { categorieId: GA }),
    vf("Le kedjenou se cuit traditionnellement dans une marmite couverte", "Vrai", "La cuisson lente à l'étouffée est la tradition.", { categorieId: GA }),
    vf("Le foutou de banane se mange avec la soupe de graine", "Vrai", null, { categorieId: GA }),
    vf("L'akpan est un dessert sucré", "Vrai", "C'est une bouillie sucrée à base de maïs fermenté.", { categorieId: GA }),
    b("Quel est le surnom donné à Abidjan par les Ivoiriens ?", "Abidjan la belle ou 'Babi'", 'FACILE', { categorieId: CI }),
    b("Comment s'appelle le quartier résidentiel aisé d'Abidjan ?", "Cocody", 'FACILE', { categorieId: CI }),
    b("Quel est le nom du marché de gros d'Abidjan ?", "Marché de Roxy ou Rambos", 'DIFFICILE', { categorieId: CI }),
    b("Comment s'appelle la grande université publique de Côte d'Ivoire ?", "Université Félix Houphouët-Boigny", 'MOYEN', { categorieId: CI }),
    b("Quel est le plus grand hôpital de Côte d'Ivoire ?", "Le CHU de Treichville", 'MOYEN', { categorieId: CI }),
    q("Quelle commune d'Abidjan est connue pour sa vie nocturne ?",
      ["Cocody", "Treichville", "Marcory", "Yopougon"],
      "Yopougon", 'FACILE', { categorieId: CI }),
    q("Quelle est l'unité de mesure populaire pour vendre le riz en CI ?",
      ["Le litre", "Le gobelet ou 'yoroton'", "Le kilogramme", "Le sac"],
      "Le gobelet ou 'yoroton'", 'FACILE', { categorieId: CI }),
    q("Quel est le nom de la cérémonie funèbre populaire en Côte d'Ivoire ?",
      ["Le deuil", "La veillée", "Le 'Gbôgô'", "Le 'Yékré'"],
      "La veillée", 'MOYEN', { categorieId: CI }),
    vf("Le SAMU ivoirien existe depuis les années 2000", "Vrai", null, { categorieId: CI }),
    vf("La Côte d'Ivoire célèbre sa fête nationale le 7 août", "Vrai", null, { categorieId: CI }),

    // ── HISTOIRE & GÉOGRAPHIE AFRIQUE (80) ─────────────────────────────────
    b("Quelle est la capitale du Sénégal ?", "Dakar", 'FACILE', { categorieId: HG }),
    b("Quelle est la capitale du Ghana ?", "Accra", 'FACILE', { categorieId: HG }),
    b("Quelle est la capitale du Nigeria ?", "Abuja", 'FACILE', { categorieId: HG }),
    b("Quel est le plus grand pays d'Afrique ?", "L'Algérie", 'MOYEN', { categorieId: HG }),
    b("Quel est le pays le plus peuplé d'Afrique ?", "Le Nigeria", 'FACILE', { categorieId: HG }),
    b("Quelle est la capitale du Burkina Faso ?", "Ouagadougou", 'FACILE', { categorieId: HG }),
    b("Quel pays africain est entouré de mer des deux côtés ?", "La Gambie", 'MOYEN', { categorieId: HG }),
    b("Quelle est la capitale de la Guinée ?", "Conakry", 'FACILE', { categorieId: HG }),
    b("Quel est le plus long fleuve d'Afrique ?", "Le Nil", 'FACILE', { categorieId: HG }),
    b("Quelle est la capitale du Mali ?", "Bamako", 'FACILE', { categorieId: HG }),
    q("Quelle est la capitale de la Guinée-Bissau ?",
      ["Bissau", "Conakry", "Banjul", "Freetown"],
      "Bissau", 'MOYEN', { categorieId: HG }),
    q("Quel pays africain est le plus riche en réserves pétrolières ?",
      ["Nigeria", "Angola", "Libye", "Gabon"],
      "Nigeria", 'FACILE', { categorieId: HG }),
    q("Quel est le plus haut sommet d'Afrique ?",
      ["Mont Kenya", "Kilimandjaro", "Mont Atlas", "Pic de l'Étoile"],
      "Kilimandjaro", 'FACILE', { categorieId: HG }),
    q("Quel fleuve traverse le Mali et le Nigeria ?",
      ["Le Niger", "Le Nil", "Le Sénégal", "Le Congo"],
      "Le Niger", 'FACILE', { categorieId: HG }),
    q("Quelle langue est officielle en Guinée Équatoriale ?",
      ["Français", "Portugais", "Espagnol et Français", "Anglais"],
      "Espagnol et Français", 'DIFFICILE', { categorieId: HG }),
    vf("L'Égypte est à la fois en Afrique et en Asie", "Vrai", "Le Sinaï est géographiquement en Asie.", { categorieId: HG }),
    vf("Le Sahara est le plus grand désert du monde", "Faux", "L'Antarctique est le plus grand désert (froid) du monde.", { categorieId: HG }),
    vf("Kwame Nkrumah était le premier président du Ghana", "Vrai", null, { categorieId: HG }),
    vf("Le Liberia a été fondé par des esclaves affranchis d'Amérique", "Vrai", null, { categorieId: HG }),
    vf("Thomas Sankara était président du Burkina Faso", "Vrai", "Il a gouverné de 1983 à 1987.", { categorieId: HG }),
    b("Quel général africain est surnommé 'le Che Guevara africain' ?", "Thomas Sankara", 'MOYEN', { categorieId: HG }),
    b("Quelle est la capitale de la Sierra Leone ?", "Freetown", 'MOYEN', { categorieId: HG }),
    b("Qui a fondé l'Organisation de l'Unité Africaine (OUA) ?", "Plusieurs présidents africains dont Nkrumah", 'DIFFICILE', { categorieId: HG }),
    b("Quelle mer borde l'Afrique du Nord ?", "La mer Méditerranée", 'FACILE', { categorieId: HG }),
    b("Quel ocean borde l'Afrique à l'ouest ?", "L'océan Atlantique", 'FACILE', { categorieId: HG }),
    q("Quelle est la capitale de l'Éthiopie ?",
      ["Nairobi", "Addis-Abeba", "Kampala", "Khartoum"],
      "Addis-Abeba", 'FACILE', { categorieId: HG }),
    q("Dans quel pays africain se trouve Victoria, le plus grand lac d'Afrique ?",
      ["Kenya uniquement", "Kenya et Tanzanie", "Ouganda, Kenya et Tanzanie", "Rwanda"],
      "Ouganda, Kenya et Tanzanie", 'DIFFICILE', { categorieId: HG }),
    q("Quel pays d'Afrique de l'Ouest n'a pas de façade maritime ?",
      ["Guinée", "Burkina Faso", "Togo", "Bénin"],
      "Burkina Faso", 'MOYEN', { categorieId: HG }),
    vf("Le Cape Town est la capitale de l'Afrique du Sud", "Faux", "Pretoria est la capitale exécutive. L'Afrique du Sud a trois capitales.", { categorieId: HG }),
    vf("Madagascar est la plus grande île d'Afrique", "Vrai", null, { categorieId: HG }),

    // ── CULTURE GÉNÉRALE & SCIENCE (20) ────────────────────────────────────
    b("Quelle planète est la plus proche du Soleil ?", "Mercure", 'FACILE', { categorieId: CG }),
    b("Combien d'os contient le corps humain adulte ?", "206", 'MOYEN', { categorieId: CG }),
    b("Quelle est la vitesse de la lumière ?", "300 000 km/s", 'MOYEN', { categorieId: ST }),
    b("Quel scientifique a découvert la pénicilline ?", "Alexander Fleming", 'MOYEN', { categorieId: ST }),
    b("Quelle est la formule chimique de l'eau ?", "H₂O", 'FACILE', { categorieId: ST }),
    q("Quelle planète a des anneaux ?",
      ["Jupiter", "Saturne", "Neptune", "Uranus"],
      "Saturne", 'FACILE', { categorieId: CG }),
    q("Combien de continents y a-t-il sur Terre ?",
      ["5", "6", "7", "8"],
      "7", 'FACILE', { categorieId: CG }),
    q("Quel est le plus petit pays du monde ?",
      ["Monaco", "Saint-Marin", "Vatican", "Liechtenstein"],
      "Vatican", 'MOYEN', { categorieId: CG }),
    vf("L'ADN est présent dans le noyau des cellules", "Vrai", null, { categorieId: ST }),
    vf("Le soleil est une étoile", "Vrai", "Le soleil est l'étoile au centre de notre système solaire.", { categorieId: CG }),

    // ── CINÉMA & MÉDIAS CI (20) ─────────────────────────────────────────────
    b("Quel est le nom de la chaîne de télévision nationale de Côte d'Ivoire ?", "RTI (Radio Télévision Ivoirienne)", 'FACILE', { categorieId: CI2 }),
    b("Quel célèbre film ivoirien a remporté des prix internationaux ?", "L'Œil du cyclone de Sékou Traoré", 'DIFFICILE', { categorieId: CI2 }),
    b("Quel acteur ivoirien est connu dans le cinéma francophone africain ?", "Isaach de Bankolé", 'DIFFICILE', { categorieId: CI2 }),
    b("Quel est le nom de la radio nationale ivoirienne ?", "Radio Côte d'Ivoire", 'FACILE', { categorieId: CI2 }),
    b("Quel journal quotidien est le plus lu en Côte d'Ivoire ?", "Fraternité Matin", 'MOYEN', { categorieId: CI2 }),
    q("Quelle chaîne TV privée ivoirienne est très populaire ?",
      ["TVA", "La Première", "NCI", "Télésud"],
      "NCI", 'MOYEN', { categorieId: CI2 }),
    q("Quel réalisateur ivoirien est connu pour ses films sur la société ivoirienne ?",
      ["Cheick Oumar Sissoko", "Henri Duparc", "Abderrahmane Sissako", "Roger Gnoan M'Bala"],
      "Henri Duparc", 'DIFFICILE', { categorieId: CI2 }),
    vf("RTI 1 est la chaîne nationale ivoirienne depuis les années 1960", "Vrai", null, { categorieId: CI2 }),
    vf("Fraternité Matin est un journal d'État ivoirien", "Vrai", null, { categorieId: CI2 }),
    vf("La Côte d'Ivoire a une industrie cinématographique active", "Vrai", "L'ICAD (Institut de Cinéma Africain et des droits de l'homme) y est actif.", { categorieId: CI2 }),

    // ── QUESTIONS SUPPLÉMENTAIRES VARIÉES (50 for total 500) ───────────────
    b("Quel est le plus grand monument de Côte d'Ivoire ?", "La Basilique Notre-Dame de la Paix à Yamoussoukro", 'FACILE', { categorieId: CI }),
    b("Quelle est la plus grande basilique chrétienne du monde ?", "La Basilique Notre-Dame de la Paix de Yamoussoukro", 'MOYEN', { categorieId: CI }),
    b("Qui a fait construire la Basilique de Yamoussoukro ?", "Félix Houphouët-Boigny", 'MOYEN', { categorieId: CI }),
    b("En quelle année la Basilique de Yamoussoukro a-t-elle été consacrée par le Pape ?", "1990", 'DIFFICILE', { categorieId: CI }),
    b("Quel est le nom complet de la Basilique de Yamoussoukro ?", "Notre-Dame de la Paix", 'MOYEN', { categorieId: CI }),
    q("Quelle université ivoirienne est la plus ancienne ?",
      ["Université de Bouaké", "Université Félix Houphouët-Boigny", "INPHB", "ESATIC"],
      "Université Félix Houphouët-Boigny", 'MOYEN', { categorieId: CI }),
    q("Quel est l'indicatif international de la Côte d'Ivoire ?",
      ["+224", "+225", "+226", "+221"],
      "+225", 'FACILE', { categorieId: CI }),
    q("Quelle plante est le symbole national de la Côte d'Ivoire sur les armoiries ?",
      ["Le cacao", "L'éléphant", "Le palmier", "Le coton"],
      "L'éléphant", 'MOYEN', { categorieId: CI }),
    vf("La Côte d'Ivoire fait partie de la zone CFA", "Vrai", null, { categorieId: CI }),
    vf("Abidjan est surnommée 'la Perle des Lagunes'", "Vrai", null, { categorieId: CI }),
    b("Quel est le nom du fondateur du groupe de musique Magic System ?", "A'salfo", 'MOYEN', { categorieId: MU }),
    b("Quel chanteur ivoirien a popularisé le terme 'vieux père' ?", "Douk Saga", 'DIFFICILE', { categorieId: MU }),
    b("Quel est le nom réel d'A'salfo de Magic System ?", "Salif Traoré", 'DIFFICILE', { categorieId: MU }),
    b("Dans quelle ville ivoirienne est né Didier Drogba ?", "Abidjan", 'MOYEN', { categorieId: SP }),
    b("Pour quel club londonien Didier Drogba a-t-il joué le plus longtemps ?", "Chelsea", 'FACILE', { categorieId: SP }),
    q("En quelle année Chelsea a-t-il remporté la Ligue des Champions avec Drogba ?",
      ["2010", "2011", "2012", "2013"],
      "2012", 'MOYEN', { categorieId: SP }),
    q("Quelle religion est majoritaire en Côte d'Ivoire ?",
      ["Le christianisme", "L'islam", "Les religions traditionnelles", "Environ 40% islam et 40% christianisme"],
      "Environ 40% islam et 40% christianisme", 'MOYEN', { categorieId: CI }),
    q("Quel ethnie est la plus représentée chez les Bété ?",
      ["Gagnoa", "Divo", "Lakota", "Gueyo"],
      "Gagnoa", 'DIFFICILE', { categorieId: CI }),
    vf("Le café est l'une des principales exportations de la Côte d'Ivoire", "Vrai", "La CI est parmi les premiers producteurs mondiaux de café Robusta.", { categorieId: CI }),
    vf("Le dioula est une langue parlée uniquement en Côte d'Ivoire", "Faux", "Le dioula est parlé dans plusieurs pays d'Afrique de l'Ouest.", { categorieId: CI }),
    b("Quel est le nom du ministre de l'Éducation nationale ivoirien nommé en 2021 ?", "Mariatou Koné", 'DIFFICILE', { categorieId: CI }),
    b("Quelle organisation africaine a son siège dans plusieurs pays membres ?", "L'UA (Union Africaine)", 'MOYEN', { categorieId: HG }),
    b("Quelle est la langue officielle de l'Union Africaine ?", "L'arabe, l'anglais, le français, le portugais, l'espagnol et le swahili", 'DIFFICILE', { categorieId: HG }),
    b("Quelle ville africaine est surnommée 'la Capitale de l'Afrique' ?", "Addis-Abeba", 'MOYEN', { categorieId: HG }),
    b("Quel pays africain a le PIB le plus élevé ?", "Le Nigeria", 'MOYEN', { categorieId: HG }),
    q("Quel est le plus grand delta du monde ?",
      ["Le delta du Nil", "Le delta du Niger", "Le delta du Gange", "Le delta du Mississippi"],
      "Le delta du Gange", 'DIFFICILE', { categorieId: CG }),
    q("Quelle invention est attribuée à un scientifique africain ?",
      ["L'ordinateur", "Le téléphone", "Le BiSCO", "Les mathématiques binaires"],
      "Les mathématiques binaires", 'DIFFICILE', { categorieId: ST }),
    vf("Le Sénégal est situé à l'ouest de la Côte d'Ivoire", "Vrai", null, { categorieId: HG }),
    vf("L'UEMOA a 8 pays membres", "Vrai", "Bénin, Burkina Faso, Guinée-Bissau, CI, Mali, Niger, Sénégal, Togo.", { categorieId: CI }),
    b("Quelle est la superficie d'Abidjan ?", "2 119 km²", 'DIFFICILE', { categorieId: CI }),
    b("Quel est le fleuve le plus long de Côte d'Ivoire ?", "Le Bandama", 'DIFFICILE', { categorieId: CI }),
    b("En quelle année a été inaugurée le 3ème pont d'Abidjan ?", "2014", 'DIFFICILE', { categorieId: CI }),
    b("Comment s'appelle le troisième pont d'Abidjan ?", "Le pont Henri Konan Bédié", 'MOYEN', { categorieId: CI }),
    b("Quel est le premier pont construit à Abidjan ?", "Le pont De Gaulle", 'DIFFICILE', { categorieId: CI }),
    q("Combien de ponts relient le Plateau et Treichville à Abidjan ?",
      ["1", "2", "3", "4"],
      "3", 'DIFFICILE', { categorieId: CI }),
    q("Quel saint est le patron d'Abidjan ?",
      ["Saint Pierre", "Saint Paul", "Sainte Marie", "Il n'y en a pas"],
      "Il n'y en a pas", 'DIFFICILE', { categorieId: CI }),
    vf("Le quartier du Plateau à Abidjan est le centre des affaires", "Vrai", null, { categorieId: CI }),
    vf("Abidjan est une ville lacustre", "Vrai", "Elle est traversée par la lagune Ébrié.", { categorieId: CI }),
    b("Quel est le nom de l'ambassade de France en Côte d'Ivoire ?", "Ambassade de France à Abidjan", 'FACILE', { categorieId: CI }),
    b("Quel pays est au nord-est de la Côte d'Ivoire ?", "Le Ghana", 'FACILE', { categorieId: CI }),
    b("Quel pays est à l'est de la Côte d'Ivoire ?", "Le Ghana", 'FACILE', { categorieId: CI }),
    b("Quel est le nom du parti politique de Laurent Gbagbo ?", "Front Populaire Ivoirien (FPI)", 'MOYEN', { categorieId: CI }),
    q("Quel est le symbole de la Côte d'Ivoire ?",
      ["Le lion", "L'éléphant", "Le léopard", "La panthère"],
      "L'éléphant", 'FACILE', { categorieId: CI }),
    q("De quelle couleur est le drapeau de la Côte d'Ivoire ?",
      ["Rouge, blanc, vert", "Orange, blanc, vert", "Jaune, vert, rouge", "Bleu, blanc, rouge"],
      "Orange, blanc, vert", 'FACILE', { categorieId: CI, explication: "De gauche à droite : orange, blanc, vert." }),
    vf("Le drapeau ivoirien est identique à celui de l'Irlande mais inversé", "Vrai", "L'irlandais est vert-blanc-orange, l'ivoirien est orange-blanc-vert.", { categorieId: CI }),
    vf("L'ASEC Mimosas est le club de football le plus titré de Côte d'Ivoire", "Vrai", null, { categorieId: SP }),
    b("Quel secteur représente la plus grande part des exportations ivoiriennes ?", "L'agriculture", 'MOYEN', { categorieId: CI }),
    b("Quel est le nom de la société d'électricité en Côte d'Ivoire ?", "CIE (Compagnie Ivoirienne d'Électricité)", 'MOYEN', { categorieId: CI }),
    b("Quel est le nom de la compagnie nationale de transport ivoirienne ?", "SOTRA", 'MOYEN', { categorieId: CI }),
    b("En quelle année l'ASEC Mimosas a-t-il remporté la Ligue des Champions africaine ?", "1998", 'DIFFICILE', { categorieId: SP }),
  ]
}
