// 50 questions vidéo — extraits YouTube sur l'Afrique et la CI
// Les videoUrl sont des placeholders — à remplacer par de vraies URLs
export function getQuestionsVideo(catMap) {
  const VD = catMap['Questions Vidéo']
  const SP = catMap['Sport']
  const GA = catMap['Gastronomie']

  const v = (enonce, reponse, choix = [], difficulte = 'MOYEN', extra = {}) => ({
    enonce,
    type: choix.length > 0 ? 'QCM' : 'BUZZER',
    reponse,
    choix,
    difficulte,
    publique: true,
    points: 200,
    tempsLimite: 30,
    tags: ['video'],
    categorieId: VD,
    videoUrl: extra.videoUrl ?? 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    videoDebut: extra.debut ?? 0,
    videoFin:   extra.fin   ?? 15,
    explication: extra.explication ?? null,
  })

  return [
    // Monuments et lieux ivoiriens (10)
    v("Identifiez ce monument visible dans cette vidéo",
      "La Basilique Notre-Dame de la Paix de Yamoussoukro",
      ["La Basilique Notre-Dame de la Paix", "La Cathédrale Saint-Paul d'Abidjan", "La Grande Mosquée d'Abidjan", "Le Musée National"],
      'FACILE'),
    v("Quel pont d'Abidjan est visible dans cet extrait ?",
      "Le Pont Félix Houphouët-Boigny (Pont De Gaulle)",
      ["Pont De Gaulle", "Pont Charles De Gaulle", "Pont HKB", "Pont Georges Pompidou"],
      'MOYEN'),
    v("Quel quartier d'Abidjan voyez-vous dans cette vidéo ?",
      "Le Plateau",
      ["Le Plateau", "Cocody", "Treichville", "Marcory"],
      'FACILE'),
    v("Identifiez ce lieu touristique naturel de Côte d'Ivoire",
      "La Forêt de Taï", [], 'DIFFICILE'),
    v("Quel marché célèbre d'Abidjan est filmé ici ?",
      "Le Marché de Cocody",
      ["Marché de Cocody", "Marché de Treichville", "Marché d'Adjamé", "Marché de Koumassi"],
      'MOYEN'),
    v("Ce parc naturel ivoirien s'appelle comment ?",
      "La Forêt du Banco",
      ["Forêt du Banco", "Parc de la Comoé", "Mont Péko", "Forêt de Yapo"],
      'MOYEN'),
    v("Quelle grande avenue d'Abidjan est visible ici ?",
      "L'Avenue du Général De Gaulle", [], 'DIFFICILE'),
    v("Ce stade ivoirien s'appelle comment ?",
      "Stade Olympique Alassane Ouattara d'Ebimpé",
      ["Stade d'Ebimpé", "Stade FHB", "Stade de Bouaké", "Stade de San-Pédro"],
      'MOYEN'),
    v("Cette plage ivoirienne est à quelle ville ?",
      "Grand-Bassam",
      ["Grand-Bassam", "Assinie", "San-Pédro", "Jacqueville"],
      'MOYEN'),
    v("Ce palais présidentiel est situé à quelle ville ?",
      "Yamoussoukro",
      ["Yamoussoukro", "Abidjan", "Bouaké", "Korhogo"],
      'FACILE'),

    // Personnalités à reconnaître (10)
    v("Identifiez cette personnalité politique ivoirienne",
      "Alassane Ouattara",
      ["Alassane Ouattara", "Laurent Gbagbo", "Henri Konan Bédié", "Guillaume Soro"],
      'FACILE'),
    v("Quel footballeur ivoirien est filmé dans ce documentaire ?",
      "Didier Drogba",
      ["Didier Drogba", "Yaya Touré", "Kolo Touré", "Gervinho"],
      'FACILE'),
    v("Identifiez cet artiste ivoirien célèbre",
      "Magic System (A'salfo)",
      ["A'salfo de Magic System", "Serge Beynaud", "DJ Arafat", "Josey"],
      'MOYEN'),
    v("Qui est cette personnalité ivoirienne des médias ?",
      "Pulchérie Gbalet", [], 'DIFFICILE'),
    v("Identifiez ce chef d'État africain dans cette archive vidéo",
      "Félix Houphouët-Boigny",
      ["Félix Houphouët-Boigny", "Léopold Sédar Senghor", "Kwame Nkrumah", "Julius Nyerere"],
      'MOYEN'),
    v("Qui est cette personnalité africaine des droits de l'homme ?",
      "Nelson Mandela",
      ["Nelson Mandela", "Desmond Tutu", "Wangari Maathai", "Kofi Annan"],
      'FACILE'),
    v("Identifiez ce joueur de football lors de ce match de CAN",
      "Yaya Touré",
      ["Yaya Touré", "Didier Drogba", "Wilfried Bony", "Jonathan Kodjia"],
      'MOYEN'),
    v("Cette personnalité africaine de la musique est qui ?",
      "Youssou Ndour",
      ["Youssou Ndour", "Baaba Maal", "Salif Keita", "Angelique Kidjo"],
      'MOYEN'),
    v("Qui est cet entrepreneur africain de la tech ?",
      "Moussa Mara", [], 'DIFFICILE'),
    v("Identifiez cette personnalité ivoirienne de la mode",
      "Pathé'O",
      ["Pathé'O", "Lamine Kouyaté", "Alphadi", "Chris Seydou"],
      'DIFFICILE'),

    // Gastronomie (10)
    v("Quel plat ivoirien est en train d'être préparé dans cette vidéo ?",
      "L'attiéké",
      ["L'attiéké", "Le foutou", "Le tô", "La semoule"],
      'FACILE', { categorieId: GA }),
    v("Identifiez ce plat ivoirien populaire",
      "Le garba",
      ["Le garba", "L'attiéké poisson", "Le kedjenou", "L'aloco"],
      'FACILE', { categorieId: GA }),
    v("Ce plat ivoirien cuit dans une marmite fermée s'appelle comment ?",
      "Le kedjenou",
      ["Le kedjenou", "Le mafé", "L'arachide poulet", "Le gboflotos"],
      'MOYEN', { categorieId: GA }),
    v("Quel fruit est en train d'être préparé dans cette recette africaine ?",
      "La banane plantain",
      ["La banane plantain", "L'igname", "Le manioc", "La patate douce"],
      'FACILE'),
    v("Ce marché de nuit à Abidjan est célèbre pour quel plat ?",
      "Le garba de nuit", [], 'DIFFICILE'),
    v("Comment s'appelle ce plat sucré-salé vu dans la vidéo ?",
      "L'aloco (banane frite)",
      ["L'aloco", "Le plantain", "Les bananes sucrées", "Les beignets"],
      'FACILE'),
    v("Cette préparation traditionnelle donne quel ingrédient ivoirien ?",
      "L'attiéké (semoule de manioc)",
      ["L'attiéké", "La farine de manioc", "L'amidon", "Le tapioca"],
      'MOYEN'),
    v("Ce restaurant typique africain s'appelle comment ?",
      "Un maquis",
      ["Un maquis", "Une brasserie", "Un bistrot", "Une gargote"],
      'FACILE'),
    v("Quelle sauce ivoirienne est préparée dans cette vidéo ?",
      "La sauce graine",
      ["La sauce graine", "La sauce arachide", "La sauce gombo", "La sauce tomate"],
      'MOYEN'),
    v("Identifiez cet aliment de base consommé en Côte d'Ivoire",
      "Le riz",
      ["Le riz", "Le mil", "Le sorgho", "Le maïs"],
      'FACILE'),

    // Scènes de films africains (10)
    v("Ce film africain est sorti en quelle décennie ?",
      "Les années 2000",
      ["Les années 1990", "Les années 2000", "Les années 2010", "Les années 1980"],
      'DIFFICILE'),
    v("Ce film nigérian (Nollywood) traite de quel sujet ?",
      "La famille et la tradition", [], 'MOYEN'),
    v("Identifiez ce réalisateur africain par son style de mise en scène",
      "Mahamat-Saleh Haroun", [], 'DIFFICILE'),
    v("Ce film sénégalais primé à Cannes est réalisé par qui ?",
      "Djibril Diop Mambéty",
      ["Djibril Diop Mambéty", "Ousmane Sembène", "Moussa Sène Absa", "Alain Gomis"],
      'DIFFICILE'),
    v("Cette série africaine très populaire est produite dans quel pays ?",
      "Nigeria (Nollywood)",
      ["Nigeria", "Ghana", "Côte d'Ivoire", "Sénégal"],
      'FACILE'),
    v("Identifiez ce film ivoirien primé internationalement",
      "Adanggaman de Roger Gnoan M'Bala", [], 'DIFFICILE'),
    v("Ce film sur la jeunesse africaine urbaine se passe dans quelle ville ?",
      "Abidjan",
      ["Abidjan", "Lagos", "Dakar", "Accra"],
      'MOYEN'),
    v("Cette scène de comédie typique ivoirienne est tirée de quel programme ?",
      "Ma Famille sur RTI", [], 'MOYEN'),
    v("Quel acteur africain reconnaissez-vous dans cet extrait ?",
      "Isaach de Bankolé",
      ["Isaach de Bankolé", "Eriq Ebouaney", "Alex Descas", "Souleymane Dème"],
      'DIFFICILE'),
    v("Cette saga télévisée africaine est célèbre dans toute l'Afrique de l'Ouest — laquelle est-ce ?",
      "Commissaire Moussa", [], 'MOYEN'),

    // Moments sportifs historiques (10)
    v("Identifiez ce but mythique de Didier Drogba",
      "But en finale de Ligue des Champions 2012",
      ["LDC 2012 contre le Bayern", "CAN 1992", "Mondial 2006", "CAN 2012"],
      'MOYEN', { categorieId: SP }),
    v("Quel match de CAN voyez-vous dans cet extrait ?",
      "Finale CAN 2024 Côte d'Ivoire vs Nigeria",
      ["CI vs Nigeria (CAN 2024)", "CI vs Ghana (CAN 2015)", "CI vs Zambie (CAN 2012)", "CI vs Mali (CAN 1994)"],
      'FACILE', { categorieId: SP }),
    v("Quel exploit sportif ivoirien est commémoré dans cette vidéo ?",
      "Première qualification en Coupe du Monde 2006", [], 'MOYEN', { categorieId: SP }),
    v("Ce moment de célébration correspond à quelle victoire ?",
      "Victoire CAN 2015 en Guinée Équatoriale",
      ["CAN 2015", "CAN 1992", "CAN 2024", "CAN 2013"],
      'MOYEN', { categorieId: SP }),
    v("Quel athlète africain bat un record dans cette vidéo ?",
      "Usain Bolt",
      ["Usain Bolt", "El Guerrouj", "Hicham El Guerrouj", "Kenenisa Bekele"],
      'FACILE', { categorieId: SP }),
    v("Identifiez ce joueur de football lors du tournoi de la CAN 2024",
      "Sébastien Haller",
      ["Sébastien Haller", "Nicolas Pépé", "Jonathan Kodjia", "Max-Alain Gradel"],
      'MOYEN', { categorieId: SP }),
    v("Dans quel stade africain ce match est-il joué ?",
      "Stade Olympique Alassane Ouattara d'Ebimpé",
      ["Stade d'Ebimpé (CI)", "Stade Léopold Sédar Senghor (SN)", "Stade d'Olembe (CM)", "Stade des Martyrs (RDC)"],
      'MOYEN', { categorieId: SP }),
    v("Ce moment de boxe africaine est avec quel champion ?",
      "Adonis Stevenson",
      ["Adonis Stevenson", "Jean Pascal", "David Lemieux", "Lucian Bute"],
      'DIFFICILE', { categorieId: SP }),
    v("Quel sport africain traditionnel est pratiqué dans cette vidéo ?",
      "La lutte sénégalaise",
      ["La lutte sénégalaise", "Le dumbe-dumbe", "La savate", "Le damba"],
      'MOYEN'),
    v("Cette cérémonie sportive africaine marque quel événement ?",
      "L'ouverture de la CAN 2024 en Côte d'Ivoire",
      ["CAN 2024 en CI", "Jeux Africains 2023", "CHAN 2022", "CAN 2021"],
      'FACILE', { categorieId: SP }),
  ]
}
