// 50 questions audio — extraits musicaux, sons à identifier
// Les audioUrl sont des placeholders — à remplacer par de vrais fichiers audio
export function getQuestionsAudio(catMap) {
  const AU = catMap['Questions Audio']
  const MU = catMap['Musique']

  const a = (enonce, reponse, choix = [], difficulte = 'MOYEN', extra = {}) => ({
    enonce,
    type: choix.length > 0 ? 'QCM' : 'BUZZER',
    reponse,
    choix,
    difficulte,
    publique: true,
    points: 150,
    tempsLimite: 25,
    tags: ['audio'],
    categorieId: AU,
    audioUrl: extra.audioUrl ?? null,
    explication: extra.explication ?? null,
  })

  return [
    // Artistes ivoiriens (20)
    a("Quel artiste ivoirien chante cet extrait de coupé-décalé ?",
      "DJ Arafat",
      ["DJ Arafat", "Serge Beynaud", "Douk Saga", "Soum Bill"],
      'FACILE'),
    a("Identifiez cet artiste qui chante en zouglou",
      "Espoir 2000",
      ["Espoir 2000", "Magic System", "Les Salopards", "Les Garagistes"],
      'MOYEN'),
    a("Quel groupe ivoirien chante '1 Femme' ?",
      "Magic System",
      ["Magic System", "Toofan", "Les Ténors", "Matrix"],
      'FACILE'),
    a("Identifiez la voix de cette artiste ivoirienne surnommée 'la Diva'",
      "Josey",
      ["Josey", "Awa Imani", "Nayanka Bell", "Teedji"],
      'MOYEN'),
    a("Cet extrait est du 'gbôfloto', quelle artiste le chante ?",
      "Nayanka Bell",
      ["Nayanka Bell", "Josey", "Awa Imani", "Dobet Gnahoré"],
      'DIFFICILE'),
    a("Reconnaissez cet artiste connu pour ses tubes en dioula",
      "Kajeem",
      ["Kajeem", "Serge Beynaud", "Awa Imani", "Stephane Kabran"],
      'DIFFICILE'),
    a("Quel artiste chante ce titre de coupé-décalé 'électro' ?",
      "Serge Beynaud",
      ["Serge Beynaud", "DJ Arafat", "Soum Bill", "Molière Brou"],
      'FACILE'),
    a("Identifiez ce morceau de gospel ivoirien",
      "Pépé Kalé", [], 'DIFFICILE'),
    a("Cet extrait appartient à quel artiste du zouglou des années 90 ?",
      "Les Salopards", [], 'DIFFICILE'),
    a("Quel artiste ivoirien chante ce titre afrobeats ?",
      "Kerozen",
      ["Kerozen", "Gradur", "Tiakola", "Iba Montana"],
      'MOYEN'),
    a("Ce style musical ivoirien s'appelle comment ?",
      "Le coupé-décalé",
      ["Le coupé-décalé", "Le zouglou", "L'afrobeats", "Le mapouka"],
      'FACILE'),
    a("Quel instrument traditionnel ivoirien entendez-vous ?",
      "Le balafon",
      ["Le balafon", "Le djembé", "La kora", "Le ngoni"],
      'MOYEN'),
    a("Identifiez le son de cet instrument à percussion africain",
      "Le djembé",
      ["Le djembé", "Le tam-tam", "Le bougarabou", "Le sabar"],
      'FACILE'),
    a("Quel est ce rythme traditionnel du nord de la Côte d'Ivoire ?",
      "Le boloye", [], 'DIFFICILE'),
    a("Cette musique traditionnelle est jouée lors de quel rituel ?",
      "La circoncision", [], 'DIFFICILE'),
    a("Reconnaissez ce titre populaire d'Arafat de 2017",
      "Paris à Miami", [], 'MOYEN'),
    a("Quel artiste africain chante ce titre afrobeats international ?",
      "Burna Boy",
      ["Burna Boy", "Wizkid", "Davido", "Afrobeats Kid"],
      'FACILE'),
    a("Identifiez ce chanteur de bikutsi camerounais",
      "Charlotte Dipanda", [], 'DIFFICILE'),
    a("Ce titre en lingala est chanté par quel artiste congolais ?",
      "Fally Ipupa",
      ["Fally Ipupa", "Koffi Olomide", "Werrason", "Fabregas"],
      'MOYEN'),
    a("Quel artiste africain chante cet hymne à la liberté ?",
      "Miriam Makeba", [], 'DIFFICILE'),

    // Instruments traditionnels (10)
    a("Quel instrument traditionnel africain entendez-vous dans cet extrait ?",
      "La kora",
      ["La kora", "Le balafon", "La ngoni", "Le xalam"],
      'MOYEN'),
    a("Ce son de percussion appartient à quel peuple d'Afrique de l'Ouest ?",
      "Les Mandingues", [], 'DIFFICILE'),
    a("Identifiez cet instrument à vent traditionnel africain",
      "Le flûteau bambou", [], 'DIFFICILE'),
    a("Quel est cet instrument à cordes pincées originaire d'Afrique ?",
      "La kora",
      ["La kora", "La guitare", "Le luth", "Le bouzouki"],
      'MOYEN'),
    a("Ce rythme de tambour correspond à quelle danse africaine ?",
      "Le sabar",
      ["Le sabar", "Le agbadza", "Le kpanlogo", "Le adowa"],
      'DIFFICILE'),
    a("Quel instrument joue cette mélodie pénétatonique africaine ?",
      "Le mbira (kalimba)",
      ["Le mbira", "Le balafon", "Le xylophone", "La flûte"],
      'MOYEN'),
    a("Ce son de cloche double est utilisé dans quelle musique africaine ?",
      "Le highlife ghanéen", [], 'DIFFICILE'),
    a("Identifiez l'instrument à vent de cet extrait musical nord-africain",
      "Le oud", [], 'DIFFICILE'),
    a("Quel instrument africain est surnommé 'la harpe africaine' ?",
      "La kora",
      ["La kora", "Le n'goni", "La sanza", "Le valiha"],
      'FACILE'),
    a("Ce son de tambour parlant appartient à quelle tradition africaine ?",
      "La tradition yoruba",
      ["La tradition yoruba", "La tradition mandingue", "La tradition bantou", "La tradition akan"],
      'DIFFICILE'),

    // Artistes africains célèbres (10)
    a("Identifiez cet artiste sénégalais de renommée mondiale",
      "Youssou Ndour",
      ["Youssou Ndour", "Baaba Maal", "Ismaël Lô", "Cheikh Lô"],
      'FACILE'),
    a("Quel artiste malien chante ce blues du désert ?",
      "Ali Farka Touré",
      ["Ali Farka Touré", "Oumou Sangaré", "Salif Keita", "Toumani Diabaté"],
      'MOYEN'),
    a("Cette voix féminine appartient à quelle artiste africaine ?",
      "Angélique Kidjo",
      ["Angélique Kidjo", "Miriam Makeba", "Fatoumata Diawara", "Charlotte Dipanda"],
      'MOYEN'),
    a("Ce style musical est le 'mbalax', originaire de quel pays ?",
      "Sénégal",
      ["Sénégal", "Gambie", "Mali", "Guinée"],
      'MOYEN'),
    a("Identifiez cet artiste nigérian de musique afrobeats",
      "Davido",
      ["Davido", "Wizkid", "Burna Boy", "Tiwa Savage"],
      'MOYEN'),
    a("Ce titre est chanteur par quel artiste afro-pop camerounais ?",
      "Locko",
      ["Locko", "Tenor", "Stanley Enow", "Salatiel"],
      'DIFFICILE'),
    a("Identifiez cet artiste congolais de rumba africaine",
      "Papa Wemba",
      ["Papa Wemba", "Koffi Olomide", "Franco Luambo", "Wendo Kolosoy"],
      'MOYEN'),
    a("Ce style de musique est originaire de quel pays africain ?",
      "Nigeria (afrobeats)",
      ["Nigeria", "Ghana", "Côte d'Ivoire", "Sénégal"],
      'FACILE'),
    a("Quel artiste chante cet hymne panafricain ?",
      "Fela Kuti", [], 'DIFFICILE'),
    a("Identifiez cet artiste français d'origine ivoirienne",
      "Aya Nakamura",
      ["Aya Nakamura", "Dadju", "Naza", "Soolking"],
      'FACILE'),

    // Hymnes nationaux africains (5)
    a("De quel pays est cet hymne national africain ?",
      "Sénégal",
      ["Sénégal", "Mali", "Guinée", "Côte d'Ivoire"],
      'DIFFICILE'),
    a("Reconnaissez l'hymne national de ce pays d'Afrique de l'Ouest",
      "Ghana",
      ["Ghana", "Nigeria", "Bénin", "Togo"],
      'DIFFICILE'),
    a("De quel pays est l'hymne national 'L'Abidjanaise' ?",
      "Côte d'Ivoire",
      ["Côte d'Ivoire", "Gabon", "Cameroun", "Congo"],
      'FACILE'),
    a("Comment s'appelle l'hymne national de la Côte d'Ivoire ?",
      "L'Abidjanaise",
      ["L'Abidjanaise", "La Marseillaise ivoirienne", "Hymne à la Paix", "Terre de nos aïeux"],
      'MOYEN'),
    a("Identifiez l'hymne national de ce pays anglophone d'Afrique de l'Ouest",
      "Nigeria",
      ["Nigeria", "Ghana", "Sierra Leone", "Liberia"],
      'MOYEN'),

    // Bonus audio (5)
    a("Quel cri d'animal entendez-vous (très présent en Côte d'Ivoire) ?",
      "Le cri du gecko",
      ["Le cri du gecko", "Le cri du caméléon", "Le cri du lézard", "Le cri de la grenouille"],
      'MOYEN'),
    a("Quel son de marché ivoirien reconnaissez-vous ?",
      "Le cri du vendeur d'attiéké", [], 'DIFFICILE'),
    a("Ce son de klaxon indique quel type de transport ivoirien ?",
      "Le gbaka (minibus)",
      ["Le gbaka", "Le taxi", "Le woro-woro", "Le bus SOTRA"],
      'MOYEN'),
    a("Identifiez ce bruit de foule typique d'un stade ivoirien",
      "Stade Félix Houphouët-Boigny d'Abidjan", [], 'DIFFICILE'),
    a("Ce chant traditionnel est entonné lors de quelle cérémonie ivoirienne ?",
      "Le mariage", [], 'DIFFICILE'),
  ]
}
