// Banque de ~1000 questions (thèmes généraux), exportée comme MODULE pour le seed
// consolidé (prisma/seed-full.js). Ce fichier ne touche plus la base lui-même.

const F = 'FACILE', M = 'MOYEN', D = 'DIFFICILE'
const b = (e, r, d, p = 100) => ({ enonce: e, type: 'BUZZER', reponse: r, difficulte: d, points: p, choix: [], tempsLimite: 30, publique: true })
const v = (e, r, d, p = 50) => ({ enonce: e, type: 'VRAI_FAUX', reponse: r, difficulte: d, points: p, choix: ['Vrai', 'Faux'], tempsLimite: 20, publique: true })
const q = (e, r, d, c, p = 100) => ({ enonce: e, type: 'QCM', reponse: r, difficulte: d, points: p, choix: c, tempsLimite: 30, publique: true })

export function getQuestions1000(catMap) {
  // catMap : { 'Géographie': id, 'Histoire': id, … }. On enveloppe en { id } pour
  // que les `geo.id`, `hist.id`… du reste du fichier restent valides sans modif.
  const geo    = { id: catMap['Géographie'] }
  const hist   = { id: catMap['Histoire'] }
  const sci    = { id: catMap['Sciences'] }
  const cine   = { id: catMap['Cinéma & Séries'] }
  const mus    = { id: catMap['Musique'] }
  const sport  = { id: catMap['Sport'] }
  const gastro = { id: catMap['Gastronomie'] }
  const litt   = { id: catMap['Littérature'] }
  const art    = { id: catMap['Art & Culture'] }
  const tech   = { id: catMap['Technologie'] }
  const nature = { id: catMap['Nature & Animaux'] }
  const cult   = { id: catMap['Culture Générale'] }

  const geoQ = [
    b('Quelle est la capitale de la France ?', 'Paris', F),
    b('Quelle est la capitale de l\'Espagne ?', 'Madrid', F),
    b('Quelle est la capitale de l\'Allemagne ?', 'Berlin', F),
    b('Quelle est la capitale de l\'Italie ?', 'Rome', F),
    b('Quelle est la capitale du Portugal ?', 'Lisbonne', F),
    b('Quelle est la capitale du Royaume-Uni ?', 'Londres', F),
    b('Quelle est la capitale de la Belgique ?', 'Bruxelles', F),
    b('Quelle est la capitale de la Suède ?', 'Stockholm', F),
    b('Quelle est la capitale de la Norvège ?', 'Oslo', F),
    b('Quelle est la capitale du Danemark ?', 'Copenhague', F),
    b('Quelle est la capitale de la Grèce ?', 'Athènes', F),
    b('Quelle est la capitale du Japon ?', 'Tokyo', F),
    b('Quelle est la capitale de la Chine ?', 'Pékin', F),
    b('Quelle est la capitale de l\'Inde ?', 'New Delhi', F),
    b('Quelle est la capitale du Mexique ?', 'Mexico', F),
    b('Quelle est la capitale de l\'Égypte ?', 'Le Caire', F),
    b('Quelle est la capitale de la Russie ?', 'Moscou', F),
    b('Quelle est la capitale des États-Unis ?', 'Washington D.C.', F),
    b('Quelle est la capitale des Pays-Bas ?', 'Amsterdam', M),
    b('Quelle est la capitale de la Suisse ?', 'Berne', M),
    b('Quelle est la capitale de la Turquie ?', 'Ankara', M),
    b('Quelle est la capitale de la Pologne ?', 'Varsovie', M),
    b('Quelle est la capitale de la Hongrie ?', 'Budapest', M),
    b('Quelle est la capitale de la Finlande ?', 'Helsinki', M),
    b('Quelle est la capitale du Canada ?', 'Ottawa', M),
    b('Quelle est la capitale du Brésil ?', 'Brasília', M),
    b('Quelle est la capitale de l\'Argentine ?', 'Buenos Aires', M),
    b('Quelle est la capitale du Maroc ?', 'Rabat', M),
    b('Quelle est la capitale de la Corée du Sud ?', 'Séoul', M),
    b('Quelle est la capitale de l\'Arabie Saoudite ?', 'Riyad', M),
    q('Quelle est la capitale de l\'Australie ?', 'Canberra', D, ['Sydney', 'Melbourne', 'Canberra', 'Brisbane']),
    q('Quelle est la capitale de la Nouvelle-Zélande ?', 'Wellington', M, ['Auckland', 'Wellington', 'Christchurch', 'Hamilton']),
    q('Quelle est la capitale du Pakistan ?', 'Islamabad', D, ['Karachi', 'Lahore', 'Islamabad', 'Peshawar']),
    q('Quelle est la capitale de l\'Ukraine ?', 'Kiev', M, ['Lviv', 'Odessa', 'Kiev', 'Kharkiv']),
    b('Quel est le plus grand pays du monde par superficie ?', 'La Russie', F),
    b('Quel est le plus petit pays du monde ?', 'Le Vatican', M),
    b('Quel est le plus grand océan du monde ?', 'L\'océan Pacifique', F),
    b('Quel est le plus haut sommet du monde ?', 'L\'Everest', F),
    b('Quel est le plus long fleuve de France ?', 'La Loire', M),
    b('Quel fleuve traverse Paris ?', 'La Seine', F),
    b('Quel est le plus long fleuve d\'Europe ?', 'La Volga', M),
    b('Dans quelle chaîne de montagnes se trouve l\'Everest ?', 'L\'Himalaya', F),
    b('Quelle est la plus haute montagne d\'Afrique ?', 'Le Kilimandjaro', M),
    b('Dans quel pays se trouve le Machu Picchu ?', 'Le Pérou', M),
    b('Dans quel pays se trouve Angkor Vat ?', 'Le Cambodge', M),
    b('Quelle est la plus grande île du monde ?', 'Le Groenland', M),
    b('Quel pays possède le plus long littoral du monde ?', 'Le Canada', D),
    b('Dans quel pays se trouvent les pyramides de Gizeh ?', 'L\'Égypte', F),
    b('Quel est le plus long fleuve du monde ?', 'L\'Amazone', D),
    b('Quel fleuve borde la frontière entre la France et l\'Allemagne ?', 'Le Rhin', M),
    q('Combien de pays composent l\'Union européenne ?', '27', M, ['25', '27', '28', '30']),
    q('Quel est le continent le plus peuplé ?', 'L\'Asie', F, ['L\'Afrique', 'L\'Asie', 'L\'Europe', 'L\'Amérique']),
    q('Quelle est la superficie de la France métropolitaine ?', '551 000 km²', M, ['451 000 km²', '551 000 km²', '651 000 km²', '751 000 km²']),
    v('Le canal de Suez relie la mer Rouge à la mer Méditerranée.', 'Vrai', F),
    v('La capitale du Brésil est São Paulo.', 'Faux', M),
    v('La mer Caspienne est le plus grand lac du monde.', 'Vrai', M),
    v('L\'Australie est à la fois un pays et un continent.', 'Vrai', F),
    v('La Chine partage une frontière avec 14 pays différents.', 'Vrai', D),
    v('La Nouvelle-Zélande est plus grande que la France.', 'Faux', M),
    v('Le Vatican est enclavé dans Rome.', 'Vrai', F),
    v('Le mont Blanc est situé à la frontière franco-italienne.', 'Vrai', M),
    v('L\'Afrique est le continent le plus vaste du monde.', 'Faux', M),
    v('Le Nil est entièrement situé en Égypte.', 'Faux', M),
    b('Quel détroit sépare l\'Europe de l\'Afrique ?', 'Le détroit de Gibraltar', M),
    b('Quel pays est traversé par le tropique du Capricorne et possède la plus grande forêt tropicale ?', 'Le Brésil', M),
    b('Quelle mer sépare l\'Italie de la Croatie ?', 'La mer Adriatique', M),
    b('Quel est le nom du plus grand désert chaud du monde ?', 'Le Sahara', F),
    b('Dans quel pays se trouve la ville de Dubaï ?', 'Les Émirats arabes unis', F),
    b('Quel pays est aussi appelé le Pays du Soleil Levant ?', 'Le Japon', F),
    b('Quel est l\'autre nom de la République populaire de Chine ?', 'La Chine continentale', M),
    b('Quel continent compte le plus grand nombre de pays ?', 'L\'Afrique', M),
    b('Dans quel pays se trouve la ville de Pétra ?', 'La Jordanie', M),
    b('Quelle montagne est aussi connue comme le « Toit du monde » ?', 'L\'Everest', F),
    b('Dans quelle ville se trouve la Tour de Pise ?', 'Pise (Toscane)', F),
    b('Quel pays partage la plus longue frontière terrestre avec la France ?', 'L\'Espagne', M),
    b('Dans quel océan se trouve Madagascar ?', 'L\'océan Indien', F),
    b('Quelle ville est connue comme la « Ville des canaux » ?', 'Venise', F),
    q('Quel est le pays le plus peuplé d\'Afrique ?', 'Le Nigeria', M, ['L\'Égypte', 'L\'Éthiopie', 'Le Nigeria', 'L\'Afrique du Sud']),
    q('Quel est le plus grand lac d\'Afrique ?', 'Le lac Victoria', M, ['Le lac Tanganyika', 'Le lac Victoria', 'Le lac Malawi', 'Le lac Turkana']),
    q('Combien de pays sont enclavés (sans accès à la mer) en Afrique ?', '16', D, ['12', '14', '16', '18']),
    b('Dans quel pays se trouvent les chutes Victoria ?', 'À la frontière Zimbabwe-Zambie', D),
    b('Quel est l\'État américain le plus grand ?', 'L\'Alaska', M),
    b('Quelle ville est la plus haute capitale du monde ?', 'La Paz (Bolivie)', D),
    b('Par quel pays passe le méridien de Greenwich ?', 'Le Royaume-Uni', M),
  ].map(o => ({ ...o, categorieId: geo.id }))

  const histQ = [
    b('En quelle année a débuté la Première Guerre mondiale ?', '1914', F),
    b('En quelle année s\'est terminée la Seconde Guerre mondiale ?', '1945', F),
    b('En quelle année a eu lieu la Révolution française ?', '1789', F),
    b('Qui était le premier président des États-Unis ?', 'George Washington', F),
    b('Qui a découvert l\'Amérique en 1492 ?', 'Christophe Colomb', F),
    b('En quelle année est tombé le mur de Berlin ?', '1989', F),
    b('Quel empire a construit le Colisée de Rome ?', 'L\'Empire romain', F),
    b('Qui était Napoléon Bonaparte ?', 'Général et Empereur des Français', F),
    b('En quelle année Napoléon a-t-il été exilé à Sainte-Hélène ?', '1815', M),
    b('Quel pharaon est associé aux grandes pyramides de Gizeh ?', 'Khéops', M),
    b('En quelle année Christophe Colomb est-il arrivé en Amérique ?', '1492', F),
    b('Qui a fondé l\'empire mongol ?', 'Gengis Khan', M),
    b('Quelle reine d\'Égypte était célèbre pour sa beauté et son intelligence ?', 'Cléopâtre', F),
    b('Qui était le roi de France pendant la Révolution française ?', 'Louis XVI', M),
    b('En quelle année Jules César a-t-il été assassiné ?', '44 avant J.-C.', M),
    b('Quel événement marque le début de la Première Guerre mondiale ?', 'L\'assassinat de l\'archiduc François-Ferdinand', M),
    b('Quel pays a lancé les bombes atomiques au Japon en 1945 ?', 'Les États-Unis', F),
    b('En quelle année a débuté la Révolution russe ?', '1917', M),
    b('Qui était le chef de l\'Allemagne nazie ?', 'Adolf Hitler', F),
    b('En quelle année a eu lieu le débarquement de Normandie ?', '1944', M),
    b('Quel est le nom de la déclaration américaine d\'indépendance signée en 1776 ?', 'Déclaration d\'indépendance', F),
    b('Qui a été le premier homme à marcher sur la Lune ?', 'Neil Armstrong', F),
    b('En quelle année Neil Armstrong a-t-il marché sur la Lune ?', '1969', F),
    b('Quel général français a dirigé la France libre pendant la Seconde Guerre mondiale ?', 'Charles de Gaulle', F),
    b('En quelle année a été fondée la Ve République française ?', '1958', M),
    b('Quel traité a mis fin à la Première Guerre mondiale ?', 'Le traité de Versailles', M),
    b('Quel empire était surnommé « l\'empire sur lequel le soleil ne se couche jamais » ?', 'L\'Empire britannique', M),
    b('Qui a inventé l\'imprimerie en Europe ?', 'Gutenberg', M),
    b('Pendant combien d\'années a duré la Guerre de Cent Ans ?', '116 ans', D),
    b('Quel conquistador a conquis l\'empire aztèque ?', 'Hernán Cortés', M),
    q('En quelle année la Tour Eiffel a-t-elle été construite ?', '1889', M, ['1880', '1885', '1889', '1895']),
    q('Qui a été le premier secrétaire général de l\'ONU ?', 'Trygve Lie', D, ['Dag Hammarskjöld', 'Kurt Waldheim', 'Trygve Lie', 'U Thant']),
    q('En quelle année l\'URSS s\'est-elle officiellement dissoute ?', '1991', M, ['1989', '1990', '1991', '1992']),
    q('Combien de rois s\'appelaient Louis en France ?', '18', D, ['14', '16', '18', '20']),
    v('La Guerre de Troie est un événement purement mythologique.', 'Faux', M),
    v('Charlemagne savait lire et écrire couramment.', 'Faux', D),
    v('Napoléon était né en France métropolitaine.', 'Faux', M),
    v('La Grande Muraille de Chine est visible depuis l\'espace à l\'œil nu.', 'Faux', M),
    v('Louis XIV a été roi de France pendant plus de 70 ans.', 'Vrai', M),
    v('La Première Guerre mondiale a duré 4 ans.', 'Vrai', F),
    v('Le Titanic a coulé en 1912.', 'Vrai', F),
    v('L\'homme a marché sur la Lune pour la première fois en 1969.', 'Vrai', F),
    b('Qui a écrit la Déclaration des droits de l\'homme et du citoyen en 1789 ?', 'L\'Assemblée nationale constituante', D),
    b('Quel roi de France a été décapité pendant la Révolution ?', 'Louis XVI', M),
    b('Quelle reine d\'Angleterre a régné le plus longtemps ?', 'La reine Élisabeth II', M),
    b('Quel pays a inventé la démocratie ?', 'La Grèce antique', F),
    b('En quelle année la Bastille a-t-elle été prise d\'assaut ?', '1789', F),
    b('Qui était le dernier pharaon d\'Égypte ?', 'Cléopâtre VII', D),
    b('Quelle guerre opposait les États-Unis au Vietnam ?', 'La guerre du Viêt Nam', F),
    b('En quelle année a eu lieu le génocide arménien ?', '1915', D),
    b('Qui a inventé le téléphone ?', 'Alexander Graham Bell', M),
    b('Quelle civilisation a construit Stonehenge ?', 'Les Celtes ou peuples néolithiques', D),
    q('Quel empire a atteint la plus grande superficie de l\'histoire ?', 'L\'empire mongol', D, ['L\'empire romain', 'L\'empire britannique', 'L\'empire mongol', 'L\'empire ottoman']),
    q('En quelle année a eu lieu l\'attentat du 11 septembre aux États-Unis ?', '2001', F, ['1998', '2000', '2001', '2003']),
    q('Qui était l\'adversaire de Napoléon à Waterloo ?', 'Wellington et Blücher', M, ['Wellington seul', 'Wellington et Blücher', 'Blücher seul', 'Alexandre Ier']),
    b('Quel est l\'autre nom de la Nuit des longs couteaux (1934) ?', 'L\'opération Kolibri', D),
    b('Qui a peint le plafond de la chapelle Sixtine ?', 'Michel-Ange', F),
    b('Quelle est la date de la Déclaration d\'indépendance américaine ?', 'Le 4 juillet 1776', F),
    b('Qui était Vercingétorix ?', 'Chef gaulois qui résista à César', M),
    b('En quelle année a eu lieu la Bataille de Marignan ?', '1515', M),
    b('Quel président américain a aboli l\'esclavage ?', 'Abraham Lincoln', F),
    b('Quel pays a subi le blocus de Berlin en 1948-1949 ?', 'L\'Allemagne de l\'Ouest (Berlin-Ouest)', M),
    b('Qui a construit le premier chemin de fer à vapeur commercial ?', 'George Stephenson', D),
    b('En quelle année Christophe Colomb est-il mort ?', '1506', D),
    v('Alexandre le Grand était d\'origine grecque.', 'Vrai', M),
    v('La Bataille de Waterloo s\'est déroulée en Belgique.', 'Vrai', M),
    v('L\'Empire romain d\'Orient a survécu jusqu\'au XVe siècle.', 'Vrai', D),
    v('Martin Luther King a reçu le prix Nobel de la paix.', 'Vrai', M),
    b('Quelle guerre a opposé la France à la Prusse en 1870-1871 ?', 'La guerre franco-prussienne', M),
    b('En quelle année a été signé l\'Armistice de la Première Guerre mondiale ?', '1918', F),
    b('Qui a découvert la vaccination contre la variole ?', 'Edward Jenner', D),
    b('Quelle est la date de la chute de Constantinople ?', '1453', D),
    b('Qui était le premier Premier ministre du Royaume-Uni ?', 'Robert Walpole', D),
  ].map(o => ({ ...o, categorieId: hist.id }))

  const sciQ = [
    b('Quelle est la formule chimique de l\'eau ?', 'H₂O', F),
    b('Quel est le symbole chimique de l\'or ?', 'Au', M),
    b('Quel est le symbole chimique du fer ?', 'Fe', M),
    b('Combien y a-t-il d\'éléments dans le tableau périodique (2024) ?', '118', D),
    b('Quelle est la vitesse de la lumière ?', '300 000 km/s', M),
    b('Qui a formulé la théorie de la relativité ?', 'Albert Einstein', F),
    b('Quel est le nom de la théorie qui explique l\'origine de l\'univers ?', 'Le Big Bang', F),
    b('Combien de chromosomes possède l\'être humain ?', '46', M),
    b('Quelle est la planète la plus proche du Soleil ?', 'Mercure', F),
    b('Quelle est la planète la plus grande du système solaire ?', 'Jupiter', F),
    b('Quel est l\'élément le plus abondant dans l\'univers ?', 'L\'hydrogène', M),
    b('Quel scientifique a découvert la pénicilline ?', 'Alexander Fleming', M),
    b('Quelle est la formule de l\'acide chlorhydrique ?', 'HCl', M),
    b('Quel est le nom du processus par lequel les plantes fabriquent leur nourriture ?', 'La photosynthèse', F),
    b('À quelle température l\'eau bout-elle à pression atmosphérique normale ?', '100°C', F),
    b('Quel est le pH d\'une solution neutre ?', '7', M),
    b('Combien de planètes compte notre système solaire ?', '8', F),
    b('Quelle planète est appelée la planète rouge ?', 'Mars', F),
    b('Qu\'est-ce que l\'ADN ?', 'L\'acide désoxyribonucléique', M),
    b('Quel gaz représente environ 78 % de l\'atmosphère terrestre ?', 'L\'azote', M),
    b('Quelle force maintient les planètes en orbite autour du Soleil ?', 'La gravité', F),
    b('Quel est le nom de la loi physique qui dit qu\'un objet en mouvement reste en mouvement ?', 'La première loi de Newton (inertie)', M),
    b('Qui a découvert la radioactivité ?', 'Marie Curie et Henri Becquerel', M),
    b('Quelle est la distance de la Terre à la Lune ?', 'Environ 384 000 km', M),
    b('Quel est le métal le plus conducteur de l\'électricité ?', 'L\'argent', M),
    q('Combien de dents l\'adulte humain possède-t-il normalement ?', '32', M, ['28', '30', '32', '34']),
    q('Quelle est la température du noyau terrestre ?', 'Environ 5 000°C', D, ['Environ 1 000°C', 'Environ 3 000°C', 'Environ 5 000°C', 'Environ 10 000°C']),
    q('Quel est le plus petit os du corps humain ?', 'L\'étrier (oreille)', M, ['La rotule', 'Le coccyx', 'L\'étrier (oreille)', 'Le sésamoïde']),
    q('Combien de litres de sang le cœur humain pompe-t-il par jour ?', 'Environ 7 000 litres', D, ['Environ 2 000 litres', 'Environ 5 000 litres', 'Environ 7 000 litres', 'Environ 10 000 litres']),
    v('Le soleil est une étoile de type naine jaune.', 'Vrai', M),
    v('L\'oreille humaine peut entendre des ultrasons.', 'Faux', F),
    v('La lumière met environ 8 minutes pour aller du Soleil à la Terre.', 'Vrai', M),
    v('L\'ADN humain est identique à 98 % à celui du chimpanzé.', 'Vrai', M),
    v('L\'eau pure conduit l\'électricité.', 'Faux', M),
    v('La Torre de Pise penche à cause de son sol argileux.', 'Vrai', M),
    b('Quel est le symbole chimique du sodium ?', 'Na', M),
    b('Qu\'est-ce que l\'effet de serre ?', 'Le réchauffement de l\'atmosphère par accumulation de gaz', M),
    b('Quel est le nom de la couche de l\'atmosphère qui nous protège des UV ?', 'La couche d\'ozone', F),
    b('Qu\'est-ce qu\'un atome ?', 'La plus petite unité d\'un élément chimique', M),
    b('Quel est le gaz responsable de l\'effet de serre le plus important ?', 'La vapeur d\'eau (ou le CO₂)', M),
    b('Quelle est la planète la plus éloignée du Soleil ?', 'Neptune', M),
    b('Qu\'est-ce qu\'une supernova ?', 'L\'explosion d\'une étoile en fin de vie', M),
    b('Quel est le nom de la galaxie qui contient notre système solaire ?', 'La Voie lactée', F),
    b('Quel organe produit l\'insuline ?', 'Le pancréas', M),
    b('Quelle est la durée d\'une journée sur Mars ?', 'Environ 24h 37min', D),
    q('Quel scientifique a proposé la théorie de l\'évolution ?', 'Charles Darwin', F, ['Isaac Newton', 'Charles Darwin', 'Gregor Mendel', 'Louis Pasteur']),
    q('Quelle molécule transporte l\'oxygène dans le sang ?', 'L\'hémoglobine', M, ['L\'albumine', 'L\'hémoglobine', 'La myoglobine', 'Le glucose']),
    q('Combien de vertèbres possède la colonne vertébrale humaine ?', '33', M, ['28', '30', '33', '36']),
    b('Quel est le nom de la particule qui donne la masse aux autres particules ?', 'Le boson de Higgs', D),
    b('Quelle est la formule chimique du CO2 ?', 'CO₂', F),
    b('À combien de degrés Celsius le fer fond-il ?', 'Environ 1 538°C', D),
    b('Qui a inventé le premier vaccin (antivariolique) ?', 'Edward Jenner', D),
    b('Qu\'est-ce que la fission nucléaire ?', 'La division d\'un noyau atomique lourd en noyaux plus légers', D),
    b('Quel est le nom du satellite naturel de la Terre ?', 'La Lune', F),
    b('Quelle est la fonction de la mitochondrie dans la cellule ?', 'La production d\'énergie (ATP)', M),
    b('Quel est l\'animal le plus rapide sur Terre ?', 'Le guépard', F),
    b('Quelle est la durée d\'une révolution de la Terre autour du Soleil ?', '365,25 jours', F),
    b('Qu\'est-ce que l\'entropie ?', 'La mesure du désordre d\'un système', D),
    b('Quel est le symbole chimique du plomb ?', 'Pb', M),
    b('Quel gaz est produit lors de la photosynthèse ?', 'L\'oxygène', F),
    b('Combien d\'os possède le squelette humain adulte ?', '206', M),
    q('Quelle planète a des anneaux visibles ?', 'Saturne', F, ['Jupiter', 'Saturne', 'Uranus', 'Mars']),
    q('Quel est l\'acide contenu dans l\'estomac ?', 'L\'acide chlorhydrique', M, ['L\'acide sulfurique', 'L\'acide chlorhydrique', 'L\'acide acétique', 'L\'acide citrique']),
    v('Le son se propage plus vite que la lumière.', 'Faux', F),
    v('L\'être humain utilise seulement 10 % de son cerveau.', 'Faux', F),
    v('Les diamants sont composés de carbone pur.', 'Vrai', M),
    b('Qu\'est-ce qu\'une éclipse solaire ?', 'La Lune passe entre la Terre et le Soleil', F),
    b('Quel élément chimique est le plus dur à l\'état naturel ?', 'Le diamant (carbone)', M),
    b('Quelle est la loi de la gravitation universelle ?', 'Deux masses s\'attirent proportionnellement à leur masse et inversement au carré de leur distance', D),
    b('Quelle est la couleur de la flamme du sodium ?', 'Jaune', M),
    b('Qui a découvert la théorie de la relativité restreinte ?', 'Albert Einstein', F),
  ].map(o => ({ ...o, categorieId: sci.id }))

  const cineQ = [
    b('Qui a réalisé le film « Titanic » (1997) ?', 'James Cameron', F),
    b('Qui a réalisé la trilogie « Le Seigneur des Anneaux » ?', 'Peter Jackson', F),
    b('Qui joue Iron Man dans les films Marvel ?', 'Robert Downey Jr.', F),
    b('Quel film a remporté le plus d\'Oscars de l\'histoire (11 Oscars) ?', 'Titanic / Ben-Hur / Le Retour du roi', M),
    b('Dans quel film Jodie Foster joue-t-elle une agente du FBI ?', 'Le Silence des agneaux', M),
    b('Qui a réalisé « Pulp Fiction » ?', 'Quentin Tarantino', M),
    b('Quel acteur joue le rôle de Jack dans Titanic ?', 'Leonardo DiCaprio', F),
    b('Dans quelle ville se déroule la série « Stranger Things » ?', 'Hawkins (Indiana)', M),
    b('Qui joue le personnage de Daenerys dans « Game of Thrones » ?', 'Emilia Clarke', M),
    b('Dans quel film entend-on la réplique « Frankly my dear, I don\'t give a damn » ?', 'Autant en emporte le vent', M),
    b('Qui a réalisé « Les Temps modernes » et « Le Dictateur » ?', 'Charlie Chaplin', M),
    b('Quel film de Spielberg met en scène des dinosaures clonés ?', 'Jurassic Park', F),
    b('Qui joue le Joker dans le film de 2019 ?', 'Joaquin Phoenix', M),
    b('Quel est le premier film de la saga « Star Wars » sorti en 1977 ?', 'Un nouvel espoir', M),
    b('Qui joue Hannibal Lecter dans « Le Silence des agneaux » ?', 'Anthony Hopkins', M),
    b('Dans quel film Audrey Hepburn chante-t-elle « Moon River » ?', 'Breakfast at Tiffany\'s', M),
    b('Qui réalise la saga « Mission : Impossible » ?', 'Brian De Palma / J.J. Abrams / Brad Bird...', D),
    b('Quel acteur joue James Bond dans « Casino Royale » (2006) ?', 'Daniel Craig', M),
    b('Quelle série se déroule dans les Îles de la Madeleine ?', 'Série de type policier canadien', D),
    b('Quel film d\'animation Pixar met en scène un rat cuisinier ?', 'Ratatouille', F),
    q('Quel acteur joue le rôle de Batman dans « The Dark Knight » ?', 'Christian Bale', M, ['Michael Keaton', 'Ben Affleck', 'Christian Bale', 'George Clooney']),
    q('Qui a réalisé « Inception » ?', 'Christopher Nolan', M, ['Steven Spielberg', 'Christopher Nolan', 'Ridley Scott', 'James Cameron']),
    q('Dans quelle ville se déroule « Breaking Bad » ?', 'Albuquerque', M, ['Los Angeles', 'Denver', 'Albuquerque', 'Phoenix']),
    q('Quel film de Stanley Kubrick est basé sur un roman de Stephen King ?', 'Shining', M, ['Orange mécanique', 'Shining', '2001 l\'Odyssée de l\'espace', 'Full Metal Jacket']),
    q('Qui joue le personnage de Hermione Granger dans Harry Potter ?', 'Emma Watson', F, ['Emma Roberts', 'Emma Watson', 'Emma Stone', 'Emma Thompson']),
    q('Quel acteur français a remporté l\'Oscar du meilleur acteur pour « The Artist » ?', 'Jean Dujardin', M, ['Vincent Cassel', 'Gad Elmaleh', 'Jean Dujardin', 'Romain Duris']),
    v('Alfred Hitchcock a joué dans la plupart de ses propres films (caméo).', 'Vrai', M),
    v('Le film « Avatar » est le film le plus rentable de l\'histoire.', 'Vrai', M),
    v('James Cameron a dirigé aussi bien Titanic qu\'Avatar.', 'Vrai', F),
    v('La série « Friends » a duré 8 saisons.', 'Faux', M),
    v('Tom Hanks a remporté deux Oscars consécutifs (1994-1995).', 'Vrai', D),
    b('Quel acteur joue le rôle de Forrest Gump ?', 'Tom Hanks', F),
    b('Dans quel film Disney entend-on la chanson « Let It Go » ?', 'La Reine des neiges', F),
    b('Quel réalisateur français a réalisé « Amélie Poulain » ?', 'Jean-Pierre Jeunet', M),
    b('Qui joue le personnage de Sherlock Holmes dans la série BBC ?', 'Benedict Cumberbatch', M),
    b('Dans quel film Colin Firth joue-t-il un roi bègue ?', 'Le Discours d\'un roi', M),
    b('Quel film a popularisé la réplique « I\'ll be back » ?', 'Terminator', M),
    b('Qui joue dans « Schindler\'s List » de Spielberg ?', 'Liam Neeson', M),
    b('Quelle série Netflix met en scène des trafiquants de drogue à Medellín ?', 'Narcos', M),
    b('Quel film de Stanley Kubrick se déroule dans l\'espace ?', '2001 : L\'Odyssée de l\'espace', M),
    b('Qui a réalisé « Le Parrain » ?', 'Francis Ford Coppola', M),
    q('Dans quel film Meryl Streep joue-t-elle une directrice de magazine de mode ?', 'Le Diable s\'habille en Prada', M, ['Kramer contre Kramer', 'Sophie\'s Choice', 'Le Diable s\'habille en Prada', 'The Iron Lady']),
    q('Quel acteur joue Jack Sparrow dans « Pirates des Caraïbes » ?', 'Johnny Depp', F, ['Orlando Bloom', 'Johnny Depp', 'Geoffrey Rush', 'Keira Knightley']),
    q('Combien d\'épisodes compte la saison 1 de « The Office » (US) ?', '6', D, ['6', '9', '12', '22']),
    b('Quel personnage est joué par Heath Ledger dans « The Dark Knight » ?', 'Le Joker', F),
    b('Dans quel film Brad Pitt et Edward Norton jouent-ils ensemble ?', 'Fight Club', M),
    b('Qui réalise « Parasite » (Palme d\'or 2019) ?', 'Bong Joon-ho', M),
    b('Quelle est la nationalité du réalisateur de « Parasite » ?', 'Coréenne (Corée du Sud)', M),
    b('Quel film est connu pour la scène du repas chez Katz\'s Delicatessen ?', 'Quand Harry rencontre Sally', M),
    b('Quel acteur joue Neo dans « Matrix » ?', 'Keanu Reeves', F),
    b('Dans quelle ville se passe principalement « Emily in Paris » ?', 'Paris', F),
    v('Le film « Psycho » d\'Hitchcock est en couleur.', 'Faux', M),
    v('La série « The Crown » est basée sur la vie de la famille royale britannique.', 'Vrai', F),
    v('Natalie Portman a été formée à Harvard.', 'Vrai', D),
    b('Quel film de Ridley Scott met en scène un gladiateur romain ?', 'Gladiator', F),
    b('Qui joue le Wolverine dans les films X-Men ?', 'Hugh Jackman', F),
    b('Quelle actrice joue Clarice Starling dans « Le Silence des agneaux » ?', 'Jodie Foster', M),
    b('Quel film d\'animation DreamWorks met en scène un ogre vert ?', 'Shrek', F),
    b('Quelle série HBO montre des cowboys androïdes dans un parc ?', 'Westworld', M),
    q('Quel acteur a joué le plus souvent James Bond ?', 'Roger Moore', D, ['Sean Connery', 'Roger Moore', 'Daniel Craig', 'Pierce Brosnan']),
    q('Dans quel film Kate Winslet joue-t-elle un personnage qui survit à un naufrage ?', 'Titanic', F, ['Eternal Sunshine', 'The Reader', 'Titanic', 'Sense and Sensibility']),
    v('Cate Blanchett a joué Galadriel dans « Le Seigneur des Anneaux ».', 'Vrai', M),
    b('Qui joue le rôle d\'Elliot dans la série « Mr. Robot » ?', 'Rami Malek', M),
    b('Dans quel film de Kubrick joue Tom Cruise avec Nicole Kidman ?', 'Eyes Wide Shut', D),
    b('Quel studio a produit la franchise « Avengers » ?', 'Marvel Studios', F),
  ].map(o => ({ ...o, categorieId: cine.id }))

  const musQ = [
    b('Quel groupe est à l\'origine de la chanson « Bohemian Rhapsody » ?', 'Queen', F),
    b('Quel chanteur est surnommé « The King » du rock ?', 'Elvis Presley', F),
    b('Qui a composé la « Cinquième Symphonie » ?', 'Ludwig van Beethoven', M),
    b('Quel groupe britannique est composé de John, Paul, George et Ringo ?', 'Les Beatles', F),
    b('Quelle chanteuse interprète « Thriller » ? (Réponse attendue : l\'album)', 'Michael Jackson', F),
    b('Quel chanteur français est connu pour « La Vie en rose » ?', 'Édith Piaf', F),
    b('Qui a composé « La Flûte enchantée » ?', 'Mozart', M),
    b('Quel artiste a sorti l\'album « Thriller » (best-seller mondial) ?', 'Michael Jackson', F),
    b('Quel groupe a sorti l\'album « Dark Side of the Moon » ?', 'Pink Floyd', M),
    b('Qui interprète « Rolling in the Deep » ?', 'Adele', F),
    b('Quel chanteur français est connu pour « Alexandrie Alexandra » ?', 'Claude François', F),
    b('Qui interprète « Purple Rain » ?', 'Prince', M),
    b('Quel groupe est derrière « Smells Like Teen Spirit » ?', 'Nirvana', M),
    b('Qui chante « Je veux » ?', 'Zaz', M),
    b('Quelle chanteuse est connue sous le nom de « Reine de la pop » ?', 'Madonna', F),
    b('Qui interprète « Shape of You » ?', 'Ed Sheeran', M),
    b('Quel artiste est derrière l\'album « Nevermind » ?', 'Nirvana', M),
    b('Qui chante « Je suis venu te dire que je m\'en vais » ?', 'Serge Gainsbourg', M),
    b('Quel chanteur belge est connu pour « Mistral Gagnant » ?', 'Renaud', M),
    b('Qui interprète « Lose Yourself » ?', 'Eminem', M),
    q('Quelle est la nationalité de Shakira ?', 'Colombienne', M, ['Vénézuélienne', 'Colombienne', 'Argentine', 'Brésilienne']),
    q('Quel instrument joue Yo-Yo Ma ?', 'Le violoncelle', M, ['Le violon', 'L\'alto', 'Le violoncelle', 'La contrebasse']),
    q('Combien de symphonies Beethoven a-t-il composées ?', '9', M, ['7', '8', '9', '10']),
    q('Qui a interprété « My Way » en anglais ?', 'Frank Sinatra', M, ['Elvis Presley', 'Frank Sinatra', 'Dean Martin', 'Bing Crosby']),
    v('Les Beatles ont débuté leur carrière à Liverpool.', 'Vrai', F),
    v('Michael Jackson n\'a jamais remporté de Grammy Award.', 'Faux', F),
    v('Mozart est mort à l\'âge de 35 ans.', 'Vrai', M),
    v('Lady Gaga s\'appelle en réalité Stefani Germanotta.', 'Vrai', M),
    v('Le groupe AC/DC est australien.', 'Vrai', M),
    b('Quel artiste français est connu pour « La Bohème » ?', 'Charles Aznavour', M),
    b('Qui chante « Papaoutai » ?', 'Stromae', M),
    b('Quel groupe est à l\'origine de « Hotel California » ?', 'Eagles', M),
    b('Qui a interprété « My Heart Will Go On » pour Titanic ?', 'Céline Dion', F),
    b('Quel artiste a sorti « 21 » (album le plus vendu des années 2010) ?', 'Adele', M),
    b('Qui interprète « Uptown Funk » ?', 'Mark Ronson ft. Bruno Mars', M),
    b('Quel rappeur est derrière l\'album « To Pimp a Butterfly » ?', 'Kendrick Lamar', D),
    b('Qui est le chanteur principal des Rolling Stones ?', 'Mick Jagger', M),
    b('Quel compositeur est surnommé « le père de la symphonie » ?', 'Joseph Haydn', D),
    b('Qui chante « Non, je ne regrette rien » ?', 'Édith Piaf', F),
    b('Quel groupe est à l\'origine de « Under the Bridge » ?', 'Red Hot Chili Peppers', M),
    q('Qui est le chanteur principal de U2 ?', 'Bono', M, ['The Edge', 'Bono', 'Larry Mullen Jr.', 'Adam Clayton']),
    q('Quel est le vrai nom de Stromae ?', 'Paul Van Haver', D, ['Paul Dumont', 'Paul Van Haver', 'Luc Dardenne', 'Samuel Degraux']),
    q('Qui a écrit l\'opéra « La Traviata » ?', 'Verdi', M, ['Puccini', 'Mozart', 'Verdi', 'Rossini']),
    b('Qui interprète « Despacito » (feat. Justin Bieber) ?', 'Luis Fonsi', M),
    b('Quel groupe est derrière « Stairway to Heaven » ?', 'Led Zeppelin', M),
    b('Qui chante « Highway to Hell » ?', 'AC/DC', M),
    b('Quel est le vrai nom de Jay-Z ?', 'Shawn Carter', D),
    b('Qui a interprété la BO de « Dirty Dancing » ?', 'Bill Medley et Jennifer Warnes', D),
    b('Quel artiste français est connu pour « Les Vieux » ?', 'Jacques Brel', M),
    v('Daft Punk est un duo français.', 'Vrai', F),
    v('Rihanna est originaire de Barbade.', 'Vrai', M),
    v('Bob Marley est né en Jamaïque.', 'Vrai', F),
    q('Quelle note vient après « ré » dans la gamme musicale ?', 'Mi', F, ['Fa', 'Sol', 'Mi', 'La']),
    q('Quel artiste a vendu le plus d\'albums de tous les temps ?', 'The Beatles', D, ['Elvis Presley', 'The Beatles', 'Michael Jackson', 'Madonna']),
    b('Qui chante « Ne me quitte pas » ?', 'Jacques Brel', M),
    b('Quel compositeur allemand était sourd quand il a composé sa Neuvième Symphonie ?', 'Beethoven', M),
    b('Qui interprète « Blinding Lights » (2020) ?', 'The Weeknd', M),
    b('Quel groupe a sorti l\'album « Abbey Road » ?', 'Les Beatles', M),
    b('Qui chante « La Vie en rose » en anglais (Édith Piaf) ?', 'Édith Piaf', F),
    b('Quel artiste français est connu pour « Aux Champs-Élysées » ?', 'Joe Dassin', M),
    b('Qui a composé « Les Quatre Saisons » ?', 'Vivaldi', M),
    b('Quel groupe est connu pour « Smells Like Teen Spirit » et « Come as You Are » ?', 'Nirvana', M),
  ].map(o => ({ ...o, categorieId: mus.id }))

  const sportQ = [
    b('Combien y a-t-il de joueurs dans une équipe de football ?', '11', F),
    b('Quel pays a remporté le plus de Coupes du monde de football ?', 'Le Brésil (5 fois)', M),
    b('En quelle année la France a-t-elle remporté la Coupe du monde ?', '1998 et 2018', M),
    b('Qui détient le record du nombre de Ballon d\'Or (7) ?', 'Lionel Messi', M),
    b('Quel joueur est surnommé « CR7 » ?', 'Cristiano Ronaldo', F),
    b('Dans quel sport Roger Federer est-il champion ?', 'Le tennis', F),
    b('Combien de sets gagnants faut-il remporter pour gagner un match en Grand Chelem (hommes) ?', '3 sets (sur 5)', M),
    b('Quel pays a remporté le plus de médailles d\'or aux Jeux olympiques depuis 1896 ?', 'Les États-Unis', M),
    b('En quelle année ont eu lieu les premiers Jeux olympiques modernes ?', '1896', M),
    b('Dans quelle ville ont eu lieu les JO de 2024 ?', 'Paris', F),
    b('Combien de joueurs compose une équipe de rugby à XV ?', '15', F),
    b('Quel joueur de basketball est surnommé « The GOAT » par ses fans ?', 'Michael Jordan ou LeBron James', M),
    b('Combien de points vaut un panier à 3 points au basketball ?', '3 points', F),
    b('Quel joueur de tennis a remporté le plus de tournois du Grand Chelem ?', 'Novak Djokovic', M),
    b('Quel coureur cycliste français a remporté le Tour de France 5 fois ?', 'Bernard Hinault', D),
    b('Quel est le sport national des États-Unis (historiquement) ?', 'Le baseball', M),
    b('Dans quel sport utilise-t-on un volant ?', 'Le badminton', F),
    b('Combien de joueurs composent une équipe de volley-ball ?', '6', M),
    b('Quel est le record du 100 m masculin ?', '9,58 s (Usain Bolt)', M),
    b('Qui détient le record du monde du 100 m ?', 'Usain Bolt', F),
    b('Dans quel pays est né Usain Bolt ?', 'La Jamaïque', M),
    b('Quel sport se pratique sur un tatami ?', 'Le judo (ou le jiu-jitsu)', F),
    b('Combien de tours compte le Tour de France ?', 'Environ 21 étapes', M),
    b('Quel est le Grand Chelem de tennis sur gazon ?', 'Wimbledon', F),
    b('Dans quelle ville se déroule Wimbledon ?', 'Londres', F),
    b('Quel footballeur brésilien est surnommé « O Rei » (Le Roi) ?', 'Pelé', F),
    b('Combien de buts Pelé a-t-il marqués en carrière officielle ?', '1 281 selon la FIFA', D),
    b('Quel pays a remporté la Coupe du monde de rugby 2019 ?', 'L\'Afrique du Sud', M),
    q('Quel pays a remporté le plus de titres de Coupe du monde de football ?', 'Le Brésil', M, ['L\'Allemagne', 'L\'Argentine', 'Le Brésil', 'L\'Italie']),
    q('Quel est le stade de foot le plus grand du monde ?', 'Le Rungrado (Corée du Nord)', D, ['Camp Nou', 'Maracanã', 'Wembley', 'Le Rungrado (Corée du Nord)']),
    q('Combien de Grand Chelem Rafael Nadal a-t-il remportés ?', '22', D, ['17', '19', '22', '20']),
    q('Dans quelle ville se déroulent les Roland-Garros ?', 'Paris', F, ['Rome', 'Paris', 'Madrid', 'Monte-Carlo']),
    v('Le football américain et le football sont le même sport.', 'Faux', F),
    v('Les Jeux olympiques d\'hiver ont lieu la même année que les Jeux olympiques d\'été.', 'Faux', M),
    v('L\'équipe de France a remporté la Coupe du monde 1998 à domicile.', 'Vrai', F),
    v('Michael Phelps est l\'athlète le plus médaillé de l\'histoire olympique.', 'Vrai', M),
    v('Le marathon mesure exactement 42,195 km.', 'Vrai', M),
    b('Qui a remporté le Tour de France 7 fois (record annulé) ?', 'Lance Armstrong', M),
    b('Quel joueur de basketball a joué avec les Chicago Bulls et les LA Lakers ?', 'Kobe Bryant', M),
    b('Dans quel sport parle-t-on de « slam dunk » ?', 'Le basketball', F),
    b('Quel pays a inventé le judo ?', 'Le Japon', F),
    b('Combien de joueurs composent une équipe de hockey sur glace ?', '6 (dont le gardien)', M),
    b('Quel sport se joue avec une raquette et une balle jaune sur un court ?', 'Le tennis', F),
    b('Quel est le sprint le plus long aux JO (athlétisme) ?', 'Le 400 m', M),
    b('Dans quel sport utilise-t-on un palet ?', 'Le hockey sur glace', F),
    b('Combien de kilomètres mesure un triathlon Ironman ?', 'Environ 226 km (natation + vélo + course)', D),
    q('Quel pays a remporté la Coupe du monde féminine de football 2023 ?', 'L\'Espagne', M, ['Les États-Unis', 'L\'Australie', 'L\'Angleterre', 'L\'Espagne']),
    q('Qui a remporté le plus de titres à Wimbledon (femmes) ?', 'Martina Navratilova (9)', D, ['Serena Williams', 'Steffi Graf', 'Martina Navratilova', 'Chris Evert']),
    q('Quel athlète a remporté l\'or au 100 m aux JO de Paris 2024 ?', 'Noah Lyles', M, ['Usain Bolt', 'Marcell Jacobs', 'Noah Lyles', 'Andre De Grasse']),
    b('Dans quel sport parle-t-on de « touché coulé » ?', 'La bataille navale (jeu)', F),
    b('Quel est le sport le plus pratiqué au monde ?', 'Le football', F),
    b('Dans quel sport Simone Biles est-elle championne ?', 'La gymnastique artistique', M),
    b('Quel joueur de tennis a remporté l\'US Open 2023 ?', 'Novak Djokovic', M),
    b('Quel club a remporté le plus de Ligues des champions de football ?', 'Le Real Madrid', M),
    b('Combien de joueurs composent une équipe de baseball ?', '9', M),
    v('Le Tour de France est exclusivement réservé aux coureurs français.', 'Faux', F),
    v('Serena Williams a remporté plus de Grand Chelem que sa sœur Venus.', 'Vrai', M),
    b('En quelle année les femmes ont-elles été admises aux JO d\'athlétisme pour la première fois ?', '1928', D),
    b('Quel est le surnom de l\'équipe nationale de rugby de Nouvelle-Zélande ?', 'Les All Blacks', F),
    q('Quel pays a remporté la Coupe du monde 2022 ?', 'L\'Argentine', M, ['La France', 'Le Brésil', 'L\'Argentine', 'La Croatie']),
    b('Quel sport est pratiqué lors des Jeux olympiques de biathlon ?', 'Ski de fond + tir à la carabine', M),
    b('Dans quel sport Teddy Riner est-il champion du monde ?', 'Le judo', M),
    b('Quel nageur français a remporté plusieurs médailles aux JO 2024 ?', 'Léon Marchand', M),
    b('Dans quel sport Zinédine Zidane a-t-il joué ?', 'Le football', F),
  ].map(o => ({ ...o, categorieId: sport.id }))

  const gastroQ = [
    b('Quelle est la sauce typique de la cuisine italienne à base de basilic, d\'ail et de pignons ?', 'Le pesto', F),
    b('De quelle région française est originaire la quiche lorraine ?', 'La Lorraine', F),
    b('Quel fromage français est surnommé « roi des fromages » ?', 'Le brie (ou le comté / roquefort selon les sources)', M),
    b('Quelle est la viande utilisée dans un coq au vin ?', 'Le poulet (coq)', F),
    b('Quel pays est le plus grand producteur de vin au monde ?', 'L\'Italie', M),
    b('De quelle région française vient le cassoulet ?', 'L\'Occitanie (Castelnaudary / Carcassonne)', M),
    b('Quel est l\'ingrédient principal du guacamole ?', 'L\'avocat', F),
    b('Quelle cuisine est à l\'origine des sushis ?', 'La cuisine japonaise', F),
    b('Quel est le fromage à pâte persillée le plus connu de France ?', 'Le roquefort', M),
    b('Quel plat espagnol est fait de riz, de fruits de mer et de safran ?', 'La paëlla', F),
    b('Quelle est la boisson nationale de l\'Italie à base d\'espresso et de lait ?', 'Le cappuccino', F),
    b('De quel pays vient la fondue savoyarde ?', 'De France (Savoie) / Suisse', F),
    b('Quel est l\'ingrédient principal du houmous ?', 'Les pois chiches', F),
    b('Quelle herbe aromatique donne sa couleur verte au pesto ?', 'Le basilic', F),
    b('Quel plat grec est composé de viande d\'agneau cuite à la broche dans un pain ?', 'Le gyros', M),
    b('De quelle région française vient le camembert ?', 'La Normandie', F),
    b('Quel dessert français est composé d\'une pâte à chou garnie de crème ?', 'L\'éclair', F),
    b('Quelle est la sauce blanche à base de béchamel, crème et fromage ?', 'La sauce Mornay', D),
    b('Quel est le vin blanc produit en Bourgogne à base de chardonnay ?', 'Le Chablis / Pouilly-Fuissé / Meursault', D),
    b('Quel alcool mexicain est distillé à partir d\'agave ?', 'La tequila (ou le mezcal)', F),
    q('Quelle est la technique culinaire qui consiste à cuire sous vide à basse température ?', 'Le sous-vide', D, ['Le confit', 'Le sous-vide', 'La vapeur', 'La basse température classique']),
    q('Quel est le fromage suisse à trous ?', 'L\'emmental', F, ['Le gruyère', 'L\'emmental', 'L\'appenzell', 'Le raclette']),
    q('Quelle épice donne sa couleur jaune au curry ?', 'Le curcuma', M, ['Le safran', 'Le curcuma', 'Le gingembre', 'La cardamome']),
    q('Quel est le cocktail à base de rhum blanc, menthe et citron vert ?', 'Le mojito', F, ['Le caïpirinha', 'Le mojito', 'Le daïquiri', 'Le Ti\'Punch']),
    v('Le champagne est produit en Champagne, région de France.', 'Vrai', F),
    v('Le wasabi est un type de gingembre vert.', 'Faux', M),
    v('La bouillabaisse est originaire de Lyon.', 'Faux', M),
    v('Le foie gras est une spécialité du Périgord et de l\'Alsace.', 'Vrai', M),
    v('La quiche lorraine ne doit pas contenir de fromage selon la recette traditionnelle.', 'Vrai', D),
    b('Quel plat marocain est cuit dans un récipient en terre cuite conique ?', 'Le tajine', M),
    b('Quelle est la boisson nationale du Japon à base de riz fermenté ?', 'Le saké', M),
    b('Quel fruit exotique est à la base du jus V8 ?', 'Les légumes (tomate, carotte…)', M),
    b('Quelle est la préparation française à base d\'œufs brouillés et de truffe ?', 'Les œufs brouillés à la truffe', D),
    b('Quel dessert français est une tarte renversée aux pommes ?', 'La tarte Tatin', M),
    b('Quel est le plat national de l\'Espagne (stew) ?', 'Le cocido madrileño', D),
    b('Quel cocktail est composé de vodka, jus de citron, cointreau et jus de cranberry ?', 'Le Cosmopolitan', M),
    b('Quelle est la sauce à base de jaune d\'œuf et d\'huile ?', 'La mayonnaise', F),
    b('Quel est le nom du repas de midi en France dans les restaurants scolaires ?', 'La cantine', F),
    b('Dans quelle région française produit-on le vin de Bordeaux ?', 'En Gironde (Nouvelle-Aquitaine)', F),
    b('Quel fromage est affiné dans des caves à Roquefort-sur-Soulzon ?', 'Le roquefort', M),
    q('Quelle est la base d\'une sauce hollandaise ?', 'Beurre clarifié et jaune d\'œuf', M, ['Crème fraîche et beurre', 'Beurre clarifié et jaune d\'œuf', 'Huile et vinaigre', 'Farine et lait']),
    q('Quel alcool est fabriqué en Écosse à partir de malt ?', 'Le whisky', F, ['Le gin', 'Le whisky', 'La vodka', 'Le rhum']),
    b('Quel est le dessert belge composé de gaufres croustillantes et de chantilly ?', 'Les gaufres de Liège ou de Bruxelles', F),
    b('Quelle est la différence entre le beurre clarifié et le ghee ?', 'Le ghee est chauffé plus longtemps pour développer un arôme noisette', D),
    b('Quel est le plat typique de la cuisine vietnamienne à base de bouillon et de nouilles ?', 'Le pho', M),
    b('Quel est le nom du pain plat indien cuit dans un tandoor ?', 'Le naan', M),
    b('Dans quelle ville est née la fondue bourguignonne ?', 'En Bourgogne (Dijon)', M),
    b('Quel alcool compose la base d\'un Negroni ?', 'Le gin', M),
    v('L\'huile d\'olive est produite principalement en Asie.', 'Faux', F),
    v('Le miso est une pâte fermentée à base de soja utilisée au Japon.', 'Vrai', M),
    v('La bière la plus consommée au monde est d\'origine mexicaine.', 'Faux', D),
    b('Quel est le plat traditionnel du Mexique à base de maïs farci ?', 'Le tamale', M),
    b('Quel légume est à la base du velouté Dubarry ?', 'Le chou-fleur', D),
    b('Quel est le nom du dessert italien à base de café et de mascarpone ?', 'Le tiramisu', F),
    q('Quelle région produit le cognac ?', 'La Charente', M, ['La Bourgogne', 'L\'Alsace', 'La Charente', 'La Champagne']),
    b('Quel est le dessert américain fait de couches de biscuits et de crème à la menthe ?', 'Le cheesecake (ou la bûche, il faut la question plus précise)', M),
    b('Quel est l\'alcool de base d\'un pisco sour ?', 'Le pisco (eau-de-vie de raisin)', M),
  ].map(o => ({ ...o, categorieId: gastro.id }))

  const littQ = [
    b('Qui a écrit « Les Misérables » ?', 'Victor Hugo', F),
    b('Qui a écrit « Madame Bovary » ?', 'Gustave Flaubert', M),
    b('Qui a écrit « L\'Étranger » ?', 'Albert Camus', M),
    b('Qui a écrit « À la recherche du temps perdu » ?', 'Marcel Proust', M),
    b('Qui a écrit « Le Petit Prince » ?', 'Antoine de Saint-Exupéry', F),
    b('Qui a écrit « Don Quichotte » ?', 'Miguel de Cervantes', M),
    b('Qui a écrit « Crime et Châtiment » ?', 'Fiodor Dostoïevski', M),
    b('Qui a écrit « 1984 » ?', 'George Orwell', M),
    b('Qui a écrit « Le Meilleur des mondes » ?', 'Aldous Huxley', M),
    b('Qui a écrit les pièces de théâtre comme « Hamlet » et « Roméo et Juliette » ?', 'William Shakespeare', F),
    b('Qui a écrit « L\'Odyssée » et « L\'Iliade » ?', 'Homère', M),
    b('Qui est l\'auteur du roman « Harry Potter » ?', 'J.K. Rowling', F),
    b('Qui a écrit « Le Rouge et le Noir » ?', 'Stendhal', M),
    b('Qui a écrit la saga « Le Seigneur des Anneaux » ?', 'J.R.R. Tolkien', M),
    b('Qui a écrit « Germinal » ?', 'Émile Zola', M),
    b('Qui a écrit « Les Fleurs du mal » ?', 'Charles Baudelaire', M),
    b('Qui a écrit « Candide » ?', 'Voltaire', M),
    b('Qui a écrit « Robinson Crusoé » ?', 'Daniel Defoe', M),
    b('Qui a écrit « Vingt mille lieues sous les mers » ?', 'Jules Verne', F),
    b('Qui est l\'auteur de « La Divine Comédie » ?', 'Dante Alighieri', M),
    b('Qui a écrit « L\'Avare » et « Le Malade imaginaire » ?', 'Molière', M),
    b('Qui a écrit « Phèdre » ?', 'Jean Racine', M),
    b('Qui est l\'auteur de « Le Cid » ?', 'Pierre Corneille', M),
    b('Qui a écrit « Les Fables » (« Le Corbeau et le Renard ») ?', 'Jean de La Fontaine', F),
    b('Qui a écrit « Ulysse » (roman moderniste) ?', 'James Joyce', D),
    q('Qui a écrit « L\'Alchimiste » ?', 'Paulo Coelho', M, ['Jorge Amado', 'Paulo Coelho', 'Gabriel García Márquez', 'Isabel Allende']),
    q('Dans quel roman apparaît le personnage de Gatsby le Magnifique ?', 'Gatsby le Magnifique', F, ['Le Soleil se lève aussi', 'Gatsby le Magnifique', 'Pour qui sonne le glas', 'L\'Adieu aux armes']),
    q('Qui a écrit « L\'Ingénu » et « Zadig » ?', 'Voltaire', M, ['Rousseau', 'Voltaire', 'Diderot', 'Montesquieu']),
    q('Dans quelle ville se déroule « Les Misérables » principalement ?', 'Paris', M, ['Lyon', 'Paris', 'Marseille', 'Bordeaux']),
    v('Albert Camus a reçu le prix Nobel de littérature.', 'Vrai', M),
    v('Victor Hugo a été enterré au Panthéon.', 'Vrai', M),
    v('Molière s\'appelait Jean-Baptiste Poquelin.', 'Vrai', M),
    v('George Orwell s\'appelait en réalité Eric Blair.', 'Vrai', D),
    v('Jules Verne a prédit Internet dans ses œuvres.', 'Vrai', D),
    b('Quel est le prénom de l\'auteur Flaubert ?', 'Gustave', M),
    b('Dans quel roman de Balzac le personnage de Rastignac apparaît-il ?', 'Le Père Goriot', M),
    b('Qui a écrit « Les Liaisons dangereuses » ?', 'Choderlos de Laclos', D),
    b('Quel poète symboliste a écrit « Le Bateau ivre » ?', 'Arthur Rimbaud', M),
    b('Qui est l\'auteur de « Voyage au bout de la nuit » ?', 'Louis-Ferdinand Céline', D),
    b('Dans quel livre apparaît le personnage de Quasimodo ?', 'Notre-Dame de Paris', F),
    b('Qui a écrit la saga « Hunger Games » ?', 'Suzanne Collins', M),
    b('Quel est l\'auteur de la série « À la croisée des mondes » ?', 'Philip Pullman', D),
    q('Qui est l\'auteur de « Cent ans de solitude » ?', 'Gabriel García Márquez', M, ['Pablo Neruda', 'Gabriel García Márquez', 'Jorge Luis Borges', 'Mario Vargas Llosa']),
    q('Quelle est la profession du personnage principal dans « Madame Bovary » ?', 'Il est médecin de campagne', M, ['Avocat', 'Médecin de campagne', 'Notaire', 'Militaire']),
    b('Qui a écrit « Poil de carotte » ?', 'Jules Renard', M),
    b('Quel auteur est à l\'origine du personnage de Hercule Poirot ?', 'Agatha Christie', F),
    b('Qui a créé Sherlock Holmes ?', 'Arthur Conan Doyle', F),
    b('Quel roman de Dostoïevski met en scène un meurtre et un étudiant ?', 'Crime et Châtiment', M),
    b('Qui est l\'auteur du « Capital » (essai économique) ?', 'Karl Marx', M),
    b('Quel roman de Zola décrit la vie dans les mines du Nord ?', 'Germinal', M),
    v('Samuel Beckett a écrit en français alors que c\'est un écrivain irlandais.', 'Vrai', D),
    v('Le nom de plume de Mary Ann Evans était George Eliot.', 'Vrai', D),
    b('Qui a écrit « Le Tour du monde en 80 jours » ?', 'Jules Verne', F),
    b('Quel poète a écrit « Demain dès l\'aube » (poème) ?', 'Victor Hugo', M),
    b('Qui a écrit la saga « Twilight » ?', 'Stephenie Meyer', M),
  ].map(o => ({ ...o, categorieId: litt.id }))

  const artQ = [
    b('Qui a peint la Joconde ?', 'Léonard de Vinci', F),
    b('Qui a peint « La Nuit étoilée » ?', 'Vincent Van Gogh', F),
    b('Qui a peint « La Persistance de la mémoire » (les montres molles) ?', 'Salvador Dalí', M),
    b('Qui a peint le plafond de la chapelle Sixtine ?', 'Michel-Ange', F),
    b('Quel architecte a conçu le Centre Pompidou ?', 'Renzo Piano et Richard Rogers', M),
    b('Qui a sculpt é « Le Penseur » ?', 'Auguste Rodin', M),
    b('Quel mouvement artistique est associé à Claude Monet ?', 'L\'impressionnisme', M),
    b('Qui a fondé le mouvement dadaïste ?', 'Hugo Ball / Tristan Tzara', D),
    b('Quel architecte a conçu le musée Guggenheim de Bilbao ?', 'Frank Gehry', D),
    b('Qui a peint « Les Demoiselles d\'Avignon » ?', 'Pablo Picasso', M),
    b('Quel mouvement artistique est associé à Picasso ?', 'Le cubisme', M),
    b('Qui a peint « Le Déjeuner sur l\'herbe » ?', 'Édouard Manet', M),
    b('Dans quel musée est exposée la Joconde ?', 'Le Louvre (Paris)', F),
    b('Qui a conçu la pyramide du Louvre ?', 'I.M. Pei', M),
    b('Quel artiste est connu pour ses sculptures de grands animaux en acier inoxydable ?', 'Jeff Koons', D),
    b('Qui a peint les « Nymphéas » ?', 'Claude Monet', M),
    b('Quel artiste de street art est connu sous le pseudonyme Banksy ?', 'Banksy (anonyme)', F),
    b('Qui a peint « Guernica » ?', 'Pablo Picasso', M),
    b('Quel style architectural caractérise les cathédrales gothiques ?', 'Les arcs-boutants et les vitraux', M),
    b('Qui a peint « Le Cri » ?', 'Edvard Munch', M),
    q('Dans quel pays est né Léonard de Vinci ?', 'Italie', F, ['France', 'Espagne', 'Italie', 'Grèce']),
    q('Quel mouvement artistique a émergé après la Seconde Guerre mondiale avec Pollock ?', 'L\'expressionnisme abstrait', D, ['Le surréalisme', 'Le pop art', 'L\'expressionnisme abstrait', 'Le minimalisme']),
    q('Qui a créé la sculpture « La Vénus de Milo » ?', 'Alexandros d\'Antioche (attribué)', D, ['Praxitèle', 'Phidias', 'Alexandros d\'Antioche', 'Lysippe']),
    v('La Tour Eiffel a d\'abord été construite comme installation temporaire.', 'Vrai', M),
    v('Michel-Ange était à la fois peintre, sculpteur et architecte.', 'Vrai', M),
    v('Andy Warhol est le fondateur du mouvement impressionniste.', 'Faux', M),
    v('La Sagrada Família de Barcelone a été conçue par Gaudí.', 'Vrai', F),
    b('Quel est le style caractéristique de Cézanne ?', 'Le post-impressionnisme', D),
    b('Dans quelle ville se trouve le musée du Prado ?', 'Madrid', M),
    b('Quel artiste est connu pour ses boîtes de soupe Campbell ?', 'Andy Warhol', M),
    b('Qui a peint « La Création d\'Adam » (sur le plafond de la Sixtine) ?', 'Michel-Ange', M),
    b('Quel architecte a conçu la Tour Eiffel ?', 'Gustave Eiffel', F),
    b('Quel est le musée le plus visité du monde ?', 'Le Louvre (Paris)', M),
    b('Qui a créé les « ready-mades » (objets du quotidien comme œuvres d\'art) ?', 'Marcel Duchamp', D),
    b('Quel est le style d\'architecture de la cathédrale Notre-Dame de Paris ?', 'Le gothique', M),
    q('Dans quel pays se trouve le musée des Offices (Uffizi) ?', 'Italie', M, ['Espagne', 'Grèce', 'Italie', 'Portugal']),
    q('Qui a peint « La Ronde de nuit » ?', 'Rembrandt', M, ['Vermeer', 'Rembrandt', 'Rubens', 'Hals']),
    v('La Joconde est peinte sur de la toile.', 'Faux', M),
    v('Van Gogh s\'est coupé une oreille.', 'Vrai', M),
    b('Quel photographe est connu pour ses portraits d\'icônes américaines des années 70 ?', 'Annie Leibovitz', D),
    b('Quel courant artistique représente la réalité de manière fragmentée ?', 'Le cubisme', M),
    b('Quel artiste japonais est connu pour ses vagues ?', 'Hokusai', M),
    b('Quel artiste a peint le « Portrait de l\'artiste à l\'oreille bandée » ?', 'Vincent Van Gogh', M),
    b('Dans quelle ville est situé le musée d\'Art moderne (MoMA) ?', 'New York', M),
    b('Quel artiste est connu pour ses sculptures géantes de fleurs en inox ?', 'Jeff Koons', D),
    b('Quel mouvement est associé au peintre Kandinsky ?', 'L\'art abstrait', D),
  ].map(o => ({ ...o, categorieId: art.id }))

  const techQ = [
    b('Qui a fondé Microsoft ?', 'Bill Gates et Paul Allen', M),
    b('Qui a fondé Apple ?', 'Steve Jobs, Steve Wozniak et Ronald Wayne', M),
    b('Qui a fondé Facebook (Meta) ?', 'Mark Zuckerberg', F),
    b('Quel langage de programmation est souvent utilisé pour le web frontend ?', 'JavaScript', M),
    b('Que signifie « HTML » ?', 'HyperText Markup Language', M),
    b('Que signifie « CPU » ?', 'Central Processing Unit', M),
    b('En quelle année le World Wide Web a-t-il été inventé ?', '1989-1991', M),
    b('Qui a inventé le World Wide Web ?', 'Tim Berners-Lee', M),
    b('Quel est le système d\'exploitation mobile de Google ?', 'Android', F),
    b('Quel est le système d\'exploitation mobile d\'Apple ?', 'iOS', F),
    b('Que signifie « Wi-Fi » ?', 'Wireless Fidelity', M),
    b('Quel jeu vidéo met en scène un plombier qui saute sur des champignons ?', 'Super Mario Bros.', F),
    b('Quel jeu vidéo est connu pour sa phrase « It\'s dangerous to go alone, take this » ?', 'The Legend of Zelda', M),
    b('Quel est le jeu vidéo le plus vendu de l\'histoire ?', 'Minecraft', M),
    b('Qui a créé le jeu Minecraft ?', 'Markus « Notch » Persson', M),
    b('Quelle console de jeu Nintendo a été lancée en 2017 ?', 'La Nintendo Switch', F),
    b('Quel réseau social est basé sur des vidéos courtes (TikTok) ?', 'TikTok', F),
    b('Quelle entreprise a développé le moteur de recherche Google ?', 'Google (Alphabet Inc.)', F),
    b('Que signifie « URL » ?', 'Uniform Resource Locator', M),
    b('Quel est le langage de programmation créé par Guido van Rossum ?', 'Python', M),
    q('En quelle année le premier iPhone a-t-il été lancé ?', '2007', M, ['2005', '2006', '2007', '2008']),
    q('Qui a fondé Tesla Motors ?', 'Elon Musk', M, ['Jeff Bezos', 'Elon Musk', 'Larry Page', 'Bill Gates']),
    q('Quel est le navigateur internet le plus utilisé au monde ?', 'Google Chrome', F, ['Mozilla Firefox', 'Safari', 'Google Chrome', 'Edge']),
    q('Combien de bits composent un octet ?', '8', M, ['4', '8', '16', '32']),
    v('Linux est un système d\'exploitation open source.', 'Vrai', M),
    v('Amazon a été fondé par Jeff Bezos.', 'Vrai', F),
    v('Le premier ordinateur personnel (PC) a été créé par Apple.', 'Faux', D),
    v('Le cryptage MD5 est considéré comme sécurisé en 2024.', 'Faux', D),
    b('Quel jeu vidéo de combat a popularisé les finishers brutaux ?', 'Mortal Kombat', M),
    b('Quel est le nom de l\'assistant vocal d\'Amazon ?', 'Alexa', F),
    b('Quel est le nom de l\'assistant vocal d\'Apple ?', 'Siri', F),
    b('Quelle entreprise a développé le chatbot ChatGPT ?', 'OpenAI', M),
    b('Quel est le jeu de battle royale développé par Epic Games ?', 'Fortnite', F),
    b('Dans quel pays se trouvent les sièges sociaux de la plupart des géants du web ?', 'Les États-Unis', F),
    b('Que signifie « IoT » ?', 'Internet of Things (Internet des objets)', M),
    b('Quel protocole permet l\'envoi d\'e-mails ?', 'SMTP', D),
    b('Quelle entreprise développe le processeur M1/M2 ?', 'Apple', M),
    b('Quel est le nom du vaisseau spatial réutilisable de SpaceX ?', 'Falcon 9 / Starship', M),
    b('En quelle année Twitter a été racheté par Elon Musk ?', '2022', M),
    q('Quel langage de programmation est principalement utilisé pour le développement iOS ?', 'Swift', M, ['Objective-C', 'Swift', 'Kotlin', 'Java']),
    q('Quel est le jeu de stratégie en temps réel le plus populaire de l\'histoire ?', 'StarCraft', D, ['Age of Empires', 'Command & Conquer', 'StarCraft', 'Warcraft']),
    v('Le Bluetooth tire son nom d\'un roi viking danois.', 'Vrai', D),
    v('Une intelligence artificielle peut réaliser n\'importe quelle tâche humaine actuellement.', 'Faux', M),
    b('Quel jeu vidéo met en scène Link dans le royaume d\'Hyrule ?', 'The Legend of Zelda', M),
    b('Quel jeu de combat est connu pour son personnage Ryu et ses « Hadouken » ?', 'Street Fighter', M),
    b('Quel est le nom de la console portable de Sony ?', 'PlayStation Portable (PSP) ou PS Vita', M),
    b('Quel est le sigle de l\'intelligence artificielle ?', 'IA (en français), AI (en anglais)', F),
    b('Que signifie « GPU » ?', 'Graphics Processing Unit', M),
    b('Quel est le langage de programmation des pages web côté serveur le plus courant ?', 'PHP, Python, Node.js…', M),
    b('Quelle entreprise a développé le système d\'exploitation Windows ?', 'Microsoft', F),
    q('Quel est le nom du premier satellite artificiel lancé dans l\'espace ?', 'Spoutnik 1', M, ['Explorer 1', 'Spoutnik 1', 'Vostok 1', 'Sputnik 2']),
    v('Le code Morse est toujours utilisé dans certaines communications maritimes.', 'Vrai', M),
    b('Quel jeu vidéo a vendu plus de 200 millions d\'exemplaires (tous supports) ?', 'Tetris', D),
    b('Quel est le réseau social professionnel le plus utilisé ?', 'LinkedIn', F),
    b('Quel est le nom de la réalité virtuelle développée par Meta ?', 'Meta Quest (anciennement Oculus)', M),
  ].map(o => ({ ...o, categorieId: tech.id }))

  const natureQ = [
    b('Quel est le mammifère terrestre le plus rapide ?', 'Le guépard', F),
    b('Quel est le plus grand mammifère terrestre ?', 'L\'éléphant d\'Afrique', F),
    b('Quel est le plus grand animal marin ?', 'La baleine bleue', F),
    b('Quel est le plus grand oiseau du monde (en hauteur) ?', 'L\'autruche', F),
    b('Quel animal est connu pour changer de couleur ?', 'Le caméléon', F),
    b('Quel est le seul mammifère capable de voler ?', 'La chauve-souris', F),
    b('Combien d\'espèces de manchots existent ?', 'Environ 18 espèces', D),
    b('Quel animal a la plus longue gestation ?', 'L\'éléphant d\'Afrique (22 mois)', M),
    b('Quel oiseau est connu pour mémoriser des milliers de caches de nourriture ?', 'Le geai bleu (ou le casse-noix)', D),
    b('Quel est l\'animal le plus venimeux au monde ?', 'La méduse de boîte (Chironex fleckeri)', D),
    b('Combien de pattes a une araignée ?', '8', F),
    b('Quel animal produit la soie ?', 'Le ver à soie (bombyx)', M),
    b('Quel est le nom scientifique du dauphin ?', 'Tursiops truncatus (grand dauphin)', D),
    b('Quel est l\'animal symbole de l\'Australie ?', 'Le kangourou', F),
    b('Quel est le seul reptile à avoir du sang chaud ?', 'Aucun — les reptiles sont à sang froid', D),
    b('Quel arbre produit les glands ?', 'Le chêne', F),
    b('Quelle est la fleur nationale de la France ?', 'Le lis (fleur de lys)', M),
    b('Quel est le plus grand primate ?', 'Le gorille', F),
    b('Quel est le nom de la science qui étudie les oiseaux ?', 'L\'ornithologie', M),
    b('Quel insecte produit le miel ?', 'L\'abeille', F),
    q('Combien d\'estomacs possède une vache ?', '4', M, ['2', '3', '4', '5']),
    q('Quel est le plus grand reptile vivant ?', 'Le crocodile marin d\'Australie', M, ['L\'anaconda', 'Le dragon de Komodo', 'Le crocodile marin d\'Australie', 'Le boa constrictor']),
    q('Quelle est la durée de vie d\'une tortue géante des Galápagos ?', 'Plus de 100 ans', M, ['50 ans', '70 ans', '100 ans', 'Plus de 100 ans']),
    q('Quel est l\'arbre à la croissance la plus rapide ?', 'Le bambou', M, ['L\'eucalyptus', 'Le bambou', 'Le saule pleureur', 'Le paulownia']),
    v('Les baleines sont des mammifères, pas des poissons.', 'Vrai', F),
    v('Les grenouilles peuvent changer de sexe.', 'Vrai', D),
    v('Le requin blanc est le plus grand poisson carnivore.', 'Vrai', M),
    v('Les pieuvres ont 3 cœurs.', 'Vrai', M),
    v('La loutre de mer se tient la patte pour ne pas dériver.', 'Vrai', M),
    b('Quel est le seul continent où vivent les pingouins en liberté ?', 'L\'Antarctique', M),
    b('Quel animal est capable de survivre dans le vide spatial (tardigrade) ?', 'Le tardigrade', D),
    b('Quel arbre est le plus vieux organisme vivant connu ?', 'Un pin bristlecone (Methuselah, ~5 000 ans)', D),
    b('Quel est le nom de la respiration des poissons ?', 'Les branchies', F),
    b('Quel animal est le plus intelligent après l\'être humain ?', 'Le dauphin (ou le chimpanzé, selon les critères)', M),
    b('Quelle plante carnivore est la plus connue ?', 'La Dionée (Venus flytrap)', M),
    b('Quel est le nom de la peur des araignées ?', 'L\'arachnophobie', M),
    b('Quel est le plus long serpent ?', 'Le python réticulé', M),
    b('Quel est l\'animal avec la plus grande envergure (oiseau) ?', 'L\'albatros hurleur', D),
    b('Quel est l\'insecte le plus dangereux au monde (nombre de morts) ?', 'Le moustique', F),
    q('Combien de tentacules possède un poulpe ?', '8', F, ['6', '8', '10', '12']),
    q('Quelle est la durée de vie moyenne d\'un chien domestique ?', '10-13 ans', F, ['5-7 ans', '8-10 ans', '10-13 ans', '15-20 ans']),
    v('L\'autruche cache sa tête dans le sable pour se protéger.', 'Faux', M),
    v('Le paresseux dort jusqu\'à 20 heures par jour.', 'Vrai', M),
    v('Les éléphants sont les seuls animaux qui ne peuvent pas sauter.', 'Vrai', M),
    b('Quel animal est à l\'origine de la rage la plus souvent transmise à l\'homme ?', 'Le chien (dans les pays en développement)', M),
    b('Quel est le cri de la grenouille ?', 'Le coassement', M),
    b('Quelle plante est connue pour purifier l\'air (NASA) ?', 'Le pothos, le spathiphyllum...', D),
    b('Quel est le seul mammifère marin avec des défenses ?', 'Le narval', D),
    b('Quel est le nom du processus par lequel les arbres perdent leurs feuilles ?', 'La défoliation / la sénescence foliaire', M),
    b('Quel animal est symbole de la France dans la nature ?', 'Le coq gaulois', F),
    q('Quelle espèce est considérée comme l\'animal le plus fort proportionnellement ?', 'Le scarabée bousier', D, ['Le gorille', 'La fourmi', 'Le scarabée bousier', 'Le rhinocéros']),
    v('Les pingouins et les manchots sont deux noms du même animal.', 'Faux', D),
    b('Quel est le plus petit mammifère ?', 'La musaraigne étrusque', D),
    b('Quel est l\'arbre national de la France ?', 'Le chêne', M),
    b('Quel est le nom de l\'étude des insectes ?', 'L\'entomologie', M),
    b('Quelle est la fleur symbole du Canada ?', 'La feuille d\'érable', F),
    b('Quel cétacé émet les chants les plus complexes ?', 'La baleine à bosse', M),
    b('Quel animal peut se régénérer entièrement depuis ses fragments ?', 'L\'étoile de mer', M),
    b('Quel est le plus grand écosystème de la planète ?', 'L\'océan (ou la forêt amazonienne selon la définition)', M),
  ].map(o => ({ ...o, categorieId: nature.id }))

  const cultQ = [
    b('Quel est le dieu du tonnerre dans la mythologie nordique ?', 'Thor', F),
    b('Qui est le dieu du soleil dans la mythologie grecque ?', 'Apollon', M),
    b('Qui est le dieu de la mer dans la mythologie grecque ?', 'Poséidon', F),
    b('Quel est le nom du roi des dieux dans la mythologie grecque ?', 'Zeus', F),
    b('Quel est le nom du roi des dieux dans la mythologie romaine ?', 'Jupiter', M),
    b('Quel héros grec a réalisé 12 travaux ?', 'Héraclès (Hercule)', F),
    b('Qui est le dieu de l\'amour dans la mythologie grecque ?', 'Éros', M),
    b('Quel est le nom du cheval ailé de la mythologie grecque ?', 'Pégase', M),
    b('Quel est le mythe qui raconte l\'histoire d\'un homme à la cire ?', 'Icare', M),
    b('Qui a écrit l\'Énéide ?', 'Virgile', M),
    b('Quelle est la langue la plus parlée dans le monde ?', 'Le mandarin (ou l\'anglais selon si on compte les locuteurs natifs)', M),
    b('Combien de langues officielles l\'ONU reconnaît-elle ?', '6', M),
    b('Quel est le code international de la France ?', '+33', F),
    b('Combien d\'heures compte un jour normal ?', '24', F),
    b('Combien de secondes y a-t-il dans une heure ?', '3 600', M),
    b('Quel est le nombre de jours dans une année bissextile ?', '366', F),
    b('Quelle est la 7e planète du système solaire ?', 'Uranus', M),
    b('Quel est le symbole du Tao ?', 'Le yin-yang', F),
    b('Combien de couleurs compte l\'arc-en-ciel ?', '7', F),
    b('Quelle est la plus grande religion au monde ?', 'Le christianisme', M),
    q('Quelle est la lettre grecque utilisée pour représenter le rapport de la circonférence au diamètre ?', 'π (pi)', M, ['α (alpha)', 'β (bêta)', 'π (pi)', 'Ω (oméga)']),
    q('Combien y a-t-il de suites de Fibonacci de 1 à 20 ?', '8 (1,1,2,3,5,8,13,21 — les premiers <20)', D, ['5', '6', '7', '8']),
    q('Quel est le signe astrologique des personnes nées le 25 décembre ?', 'Capricorne', M, ['Sagittaire', 'Capricorne', 'Verseau', 'Poisson']),
    q('Quelle monnaie était utilisée en France avant l\'euro ?', 'Le franc', F, ['Le louis', 'Le franc', 'L\'écu', 'La livre']),
    v('L\'euro a été introduit le 1er janvier 2002 (billets et pièces).', 'Vrai', M),
    v('La Bible est le livre le plus vendu de l\'histoire.', 'Vrai', F),
    v('Le signe « & » (esperluette) vient de la ligature du mot latin « et ».', 'Vrai', D),
    v('Un octopode a 10 bras.', 'Faux', F),
    b('Quel est le symbole chimique de l\'or en français ?', 'Au (aurum)', M),
    b('Quelle est la devise de la France ?', 'Liberté, Égalité, Fraternité', F),
    b('Quel est l\'hymne national de la France ?', 'La Marseillaise', F),
    b('Qui a inventé le calcul infinitésimal ?', 'Newton et Leibniz (simultanément)', D),
    b('Quelle est la langue officielle du Brésil ?', 'Le portugais', M),
    b('Quel est le nom du Parlement français ?', 'L\'Assemblée nationale et le Sénat', M),
    b('Quel est l\'emblème national de la France ?', 'La Marianne (et le coq gaulois)', M),
    b('Combien de juges siègent à la Cour suprême des États-Unis ?', '9', M),
    b('Quel est le plus grand aquifère de la planète ?', 'L\'aquifère Ogallala (États-Unis)', D),
    b('Quel est le prénom de l\'inventeur de l\'imprimerie ?', 'Johannes (Gutenberg)', M),
    b('Quelle est la dénomination complète de l\'ONU ?', 'Organisation des Nations Unies', F),
    b('Quel est le cri du lion ?', 'Le rugissement', F),
    q('Quel est le document fondateur de l\'Union européenne ?', 'Le traité de Rome', D, ['Le traité de Maastricht', 'Le traité de Rome', 'Le traité de Lisbonne', 'La Déclaration de Schuman']),
    q('Combien d\'étoiles compte le drapeau européen ?', '12', M, ['9', '10', '12', '15']),
    v('Le chinois mandarin s\'écrit de gauche à droite.', 'Vrai', M),
    v('Le Vatican est membre des Nations Unies.', 'Faux', D),
    b('Quel est le plus grand temple bouddhiste du monde ?', 'Borobudur (Indonésie)', D),
    b('Quel est l\'événement annuel qui célèbre le début de l\'année lunaire en Chine ?', 'Le Nouvel An chinois', F),
    b('Quelle est la religion majoritaire en Inde ?', 'L\'hindouisme', M),
    b('Quel est le livre sacré de l\'islam ?', 'Le Coran', F),
    b('Quel est le livre sacré du christianisme ?', 'La Bible', F),
    b('Quel est le livre sacré du judaïsme ?', 'La Torah (ou le Tanakh)', M),
    b('Quel est le livre sacré du bouddhisme ?', 'Le Tripitaka (ou le Dhammapada)', D),
    q('Quelle est la monnaie officielle du Japon ?', 'Le yen', F, ['Le yuan', 'Le yen', 'Le won', 'Le ringgit']),
    q('Quel est le signe astrologique de la balance ?', 'Celui des personnes nées entre le 23 sept. et le 22 oct.', M, ['Scorpion', 'Vierge', 'Balance', 'Lion']),
    v('L\'alphabet latin comporte 26 lettres.', 'Vrai', F),
    v('La France est membre permanent du Conseil de sécurité de l\'ONU.', 'Vrai', M),
    b('Quel est le symbole « @ » appelé en français ?', 'L\'arobase', M),
    b('Quel est le nom de la monnaie officielle du Royaume-Uni ?', 'La livre sterling', F),
    b('Quel est le premier pays à avoir accordé le droit de vote aux femmes ?', 'La Nouvelle-Zélande (1893)', D),
    b('Quel est le continent où se trouve le pays d\'origine des aurores boréales ?', 'L\'Europe du Nord / le pôle Nord', M),
    b('Quel numéro d\'urgence appelle-t-on pour le SAMU en France ?', 'Le 15', F),
    b('Quel est le numéro d\'urgence pompiers en France ?', 'Le 18', F),
    b('Quel est le numéro d\'urgence européen unique ?', 'Le 112', M),
    b('Quel est le préfixe «kilo» en puissance de 10 ?', '10³ (1 000)', M),
    b('Quel est l\'anagramme du mot « chien » ?', 'Niche', M),
  ].map(o => ({ ...o, categorieId: cult.id }))

  const extraGeoQ = [
    b('Quel est le deuxième plus grand pays du monde ?', 'Le Canada', M),
    b('Dans quel continent se trouve le Kenya ?', 'L\'Afrique', F),
    b('Quelle est la capitale de la Thaïlande ?', 'Bangkok', M),
    b('Quel est le nom du plus long mur construit par l\'homme ?', 'La Grande Muraille de Chine', F),
    b('Quel pays est composé de plus de 17 000 îles ?', 'L\'Indonésie', M),
    b('Quelle est la capitale de la Colombie ?', 'Bogotá', M),
    b('Dans quel pays se trouve le mont Fuji ?', 'Le Japon', F),
    b('Quel est l\'autre nom de la mer Morte ?', 'La mer de Sel', D),
    b('Dans quel pays se trouvent les fjords les plus célèbres ?', 'La Norvège', F),
    b('Quelle est la capitale du Chili ?', 'Santiago', M),
    b('Quelle rivière forme la frontière naturelle entre les États-Unis et le Mexique ?', 'Le Rio Grande', M),
    b('Dans quel pays se trouve la ville d\'Istanbul ?', 'La Turquie', F),
    b('Quel est le plus petit continent ?', 'L\'Océanie', F),
    b('Quelle est la capitale de l\'Iran ?', 'Téhéran', M),
    b('Quelle ville est surnommée la « Ville des anges » aux États-Unis ?', 'Los Angeles', F),
    b('Quel est le plus long fleuve d\'Asie ?', 'Le Yangtsé', M),
    b('Dans quel pays se trouvent les ruines de Machu Picchu ?', 'Le Pérou', M),
    b('Quelle est la capitale du Pérou ?', 'Lima', M),
    q('Quel pays partage ses frontières avec la France, l\'Allemagne et l\'Italie ?', 'La Suisse', M, ['La Belgique', 'L\'Autriche', 'La Suisse', 'Le Luxembourg']),
    v('Madagascar est une île de l\'océan Pacifique.', 'Faux', M),
    v('La mer Noire n\'est pas reliée à l\'océan Atlantique.', 'Faux', D),
  ].map(o => ({ ...o, categorieId: geo.id }))

  const extraHistQ = [
    b('Quel pharaon est associé au masque funéraire le plus célèbre ?', 'Toutânkhamon', M),
    b('En quelle année Rome a-t-elle été fondée (selon la tradition) ?', '753 avant J.-C.', D),
    b('Qui était la première femme à diriger un gouvernement démocratique ?', 'Sirimavo Bandaranaike (Sri Lanka, 1960)', D),
    b('Quel empire a construit la Route de la soie ?', 'L\'empire han (Chine)', D),
    b('En quelle année la Première Croisade a-t-elle eu lieu ?', '1096', D),
    b('Quel général romain a traversé le Rubicon en 49 avant J.-C. ?', 'Jules César', M),
    b('En quelle année a eu lieu la bataille de Trafalgar ?', '1805', D),
    b('Qui a fondé l\'empire ottoman ?', 'Osman Ier', D),
    b('Quel scientifique a été condamné par l\'Inquisition pour avoir soutenu que la Terre tournait autour du Soleil ?', 'Galilée', M),
    b('Quel président américain a introduit le New Deal ?', 'Franklin D. Roosevelt', M),
    b('En quelle année la Chine est-elle devenue communiste ?', '1949', M),
    b('Quel est le nom de l\'opération militaire du débarquement en Normandie ?', 'Opération Overlord', M),
    b('Qui était le dernier tsar de Russie ?', 'Nicolas II', M),
    b('En quelle année a eu lieu la révolution américaine ?', '1776', M),
    b('Quel explorateur portugais a contourné l\'Afrique pour atteindre les Indes ?', 'Vasco de Gama', M),
    q('En quelle année a eu lieu la Révolution culturelle en Chine ?', '1966', D, ['1949', '1956', '1966', '1972']),
    q('Quelle est la date de la prise de la Bastille ?', '14 juillet 1789', F, ['4 juillet 1789', '14 juillet 1789', '14 juillet 1793', '5 mai 1789']),
    v('La guerre de Sécession américaine a duré 5 ans.', 'Faux', M),
    v('Cléopâtre était d\'origine grecque (macédonienne).', 'Vrai', D),
    v('Napoléon était plus petit que la moyenne de son époque.', 'Faux', D),
  ].map(o => ({ ...o, categorieId: hist.id }))

  const extraSciQ = [
    b('Qu\'est-ce que la loi d\'Ohm ?', 'U = R × I (tension = résistance × intensité)', M),
    b('Quel est le nom de la particule élémentaire sans masse qui transporte la lumière ?', 'Le photon', M),
    b('Qu\'est-ce que l\'osmose ?', 'Le passage d\'eau à travers une membrane semi-perméable', M),
    b('Quelle est l\'unité de mesure de la fréquence ?', 'Le hertz (Hz)', M),
    b('Quel est le nom de la théorie des cordes en physique ?', 'La théorie des supercordes', D),
    b('Quel est le plus léger des gaz ?', 'L\'hydrogène', M),
    b('Qu\'est-ce que l\'effet Doppler ?', 'Le changement de fréquence d\'une onde quand la source ou l\'observateur se déplace', M),
    b('Quelle est l\'unité SI de la pression ?', 'Le pascal (Pa)', M),
    b('Combien d\'os possède le crâne humain ?', '22', D),
    b('Quel est le nom de l\'organe qui filtre le sang et produit l\'urine ?', 'Le rein', F),
    b('Quelle est la particule de charge négative ?', 'L\'électron', F),
    b('Qu\'est-ce que le point d\'ébullition ?', 'La température à laquelle un liquide se transforme en vapeur', F),
    q('Quel est l\'élément chimique de numéro atomique 1 ?', 'L\'hydrogène', F, ['L\'hélium', 'L\'hydrogène', 'Le lithium', 'Le carbone']),
    q('Quelle est la vitesse du son dans l\'air à 20°C ?', '340 m/s', M, ['200 m/s', '280 m/s', '340 m/s', '400 m/s']),
    v('L\'oxygène est incolore et inodore à température ambiante.', 'Vrai', M),
    v('Le cerveau humain utilise 20 % de l\'énergie du corps.', 'Vrai', D),
    v('La foudre frappe la Tour Eiffel en moyenne 20 fois par an.', 'Vrai', D),
    b('Qu\'est-ce qu\'un neutron ?', 'Une particule sans charge du noyau atomique', M),
    b('Quel est le nom du processus de division cellulaire ?', 'La mitose (ou la méiose)', M),
    b('Quelle est la formule chimique du dioxyde de carbone ?', 'CO₂', F),
  ].map(o => ({ ...o, categorieId: sci.id }))

  const extraCineQ = [
    b('Quel film de Stanley Kubrick est inspiré du roman de Nabokov ?', 'Lolita (1962)', D),
    b('Qui joue Vincent Vega dans « Pulp Fiction » ?', 'John Travolta', M),
    b('Quel film Pixar met en scène deux robots dans un monde post-apocalyptique ?', 'WALL-E', M),
    b('Qui réalise « Interstellar » ?', 'Christopher Nolan', M),
    b('Quel acteur joue le personnage principal dans la série « Peaky Blinders » ?', 'Cillian Murphy', M),
    b('Dans quel film Adam Sandler joue-t-il un professeur de lycée ?', 'Happy Gilmore / Billy Madison...', M),
    b('Quel film d\'horreur se passe dans l\'Overlook Hotel ?', 'Shining', M),
    b('Qui joue Atticus Finch dans « To Kill a Mockingbird » ?', 'Gregory Peck', D),
    b('Quelle série se passe dans un hôpital de Chicago ?', 'E.R. (Urgences)', M),
    b('Qui a réalisé « La Dolce Vita » ?', 'Federico Fellini', M),
    b('Dans quel film entend-on la phrase « Hasta la vista, baby » ?', 'Terminator 2', M),
    b('Quel film raconte l\'histoire de l\'équipe nationale de rugby néo-zélandaise ?', 'Invictus (non, c\'est le rugby sud-africain)', D),
    b('Quel acteur français a joué dans « Intouchables » ?', 'François Cluzet et Omar Sy', F),
    b('Dans quelle ville se déroule la série « Lupin » (Netflix) ?', 'Paris', F),
    b('Qui joue le détective Morse dans la série éponyme ?', 'Kevin Whately', D),
    q('Quelle actrice a joué dans « Alien » (1979) ?', 'Sigourney Weaver', M, ['Jodie Foster', 'Sigourney Weaver', 'Meryl Streep', 'Susan Sarandon']),
    q('Quel film a remporté la Palme d\'or à Cannes en 2019 ?', 'Parasite', M, ['Burning', 'Once Upon a Time in Hollywood', 'Parasite', 'The Lighthouse']),
    v('Le film « La Grande Illusion » de Jean Renoir se passe durant la Première Guerre mondiale.', 'Vrai', D),
    v('Scarlett Johansson a été nominée aux Oscars.', 'Vrai', M),
    b('Quel film de Miyazaki met en scène une jeune sorcière qui livre des colis ?', 'Kiki la petite sorcière', M),
    b('Quel film de Tim Burton met en scène un personnage aux mains en ciseau ?', 'Edward aux mains d\'argent', M),
  ].map(o => ({ ...o, categorieId: cine.id }))

  const extraMusQ = [
    b('Quel compositeur français est connu pour « Boléro » ?', 'Maurice Ravel', M),
    b('Qui chante « Thriller » (chanson) ?', 'Michael Jackson', F),
    b('Quel groupe est à l\'origine de « Nothing Else Matters » ?', 'Metallica', M),
    b('Qui interprète « Someone Like You » ?', 'Adele', M),
    b('Quel chanteur est surnommé « The Boss » ?', 'Bruce Springsteen', M),
    b('Quel groupe a sorti « Creep » ?', 'Radiohead', M),
    b('Qui est la chanteuse principale de « Dreams » (Fleetwood Mac) ?', 'Stevie Nicks', M),
    b('Quel artiste a popularisé le reggae dans le monde entier ?', 'Bob Marley', F),
    b('Qui chante « Gangsta\'s Paradise » ?', 'Coolio', M),
    b('Quel est l\'instrument de musique national de l\'Écosse ?', 'La cornemuse', F),
    b('Qui interprète « Un homme heureux » ?', 'William Sheller', D),
    b('Quel groupe français a sorti « Sébastopol » ?', 'Indochine', M),
    b('Quel compositeur est connu pour sa Toccata et Fugue en ré mineur ?', 'Jean-Sébastien Bach', M),
    b('Qui chante « Les Corons » ?', 'Pierre Bachelet', M),
    b('Quel groupe est derrière « Under Pressure » (avec David Bowie) ?', 'Queen', M),
    q('Quel musicien était connu sous le nom de « Satchmo » ?', 'Louis Armstrong', M, ['Miles Davis', 'Duke Ellington', 'Louis Armstrong', 'Charlie Parker']),
    q('Dans quelle ville est né Frédéric Chopin ?', 'Varsovie (Pologne)', M, ['Paris', 'Vienne', 'Varsovie (Pologne)', 'Prague']),
    v('Les Daft Punk se sont séparés en 2021.', 'Vrai', M),
    v('Beethoven est né à Paris.', 'Faux', M),
    b('Quel artiste a sorti « Flowers » (2023) ?', 'Miley Cyrus', M),
    b('Quelle chanteuse française est connue pour sa voix et son franc-parler sur scène ?', 'Zazie ou Christophe Maé...', M),
  ].map(o => ({ ...o, categorieId: mus.id }))

  const extraSportQ = [
    b('Dans quel sport parle-t-on de « grand chelem » au tennis ?', 'Le tennis', F),
    b('Quel pays a remporté la Coupe du monde de cricket le plus souvent ?', 'L\'Australie', D),
    b('Dans quel sport Tony Hawk est-il célèbre ?', 'Le skateboard', M),
    b('Quel est le record du monde du saut en longueur ?', '8,95 m (Mike Powell, 1991)', D),
    b('Quel club anglais est surnommé « The Reds » ?', 'Liverpool FC', M),
    b('Dans quel pays se tient le Grand Prix de Monaco (F1) ?', 'À Monaco', F),
    b('Quel est le sport où on utilise un stick pour frapper une balle vers des cages ?', 'Le hockey sur gazon', M),
    b('Qui a remporté le plus de titres en F1 (7 championnats) ?', 'Lewis Hamilton et Michael Schumacher', M),
    b('Quel footballeur est surnommé « La Pulga » (la puce) ?', 'Lionel Messi', M),
    b('Dans quel sport Katie Ledecky est-elle championne ?', 'La natation', M),
    b('Quel est le plus long parcours de golf en nombre de trous standard ?', '18 trous', F),
    b('Combien de sets gagne-t-on pour remporter un match à Wimbledon (femmes) ?', '2 sets', M),
    b('Quel est le titre le plus convoité du rugby des nations ?', 'La Coupe du monde de rugby', M),
    b('Dans quel pays est né Pelé ?', 'Le Brésil', F),
    q('Quel athlète a remporté l\'or au saut à la perche à Paris 2024 ?', 'Armand Duplantis', M, ['Renaud Lavillenie', 'Sam Kendricks', 'Armand Duplantis', 'Chris Nilsen']),
    q('En quelle année Lewis Hamilton a-t-il remporté son premier titre F1 ?', '2008', D, ['2005', '2007', '2008', '2010']),
    v('L\'équipe de France a perdu la finale de la Coupe du monde 2006.', 'Vrai', M),
    v('Les Jeux olympiques ont été annulés deux fois à cause des guerres mondiales.', 'Vrai', M),
    b('Quel est le plus grand stade de football du monde ?', 'Le stade Rungrado (Corée du Nord)', D),
    b('Dans quel sport le « butterfly » est-il une nage ?', 'La natation (le papillon)', F),
    b('Quel est le nom du ballon de rugby ?', 'Un ballon ovale', F),
  ].map(o => ({ ...o, categorieId: sport.id }))

  const extraGastroQ = [
    b('Quel est le plat national de l\'Allemagne ?', 'La choucroute (Sauerkraut)', M),
    b('Quelle épice est la plus chère du monde ?', 'Le safran', M),
    b('Quel fromage est à la base de la pizza Margherita ?', 'La mozzarella', F),
    b('Quelle est la différence entre la crème brûlée et la panna cotta ?', 'La crème brûlée est française avec caramel, la panna cotta est italienne', D),
    b('Quel est le plat traditionnel de la Louisiane à base de fruits de mer et de riz ?', 'Le jambalaya', M),
    b('Dans quel pays mange-t-on du kimchi ?', 'En Corée du Sud', M),
    b('Quel est le nom du pain traditionnel irlandais à base de farine de seigle ?', 'Le brown bread (soda bread)', D),
    b('Quelle est la boisson alcoolisée traditionnelle de Russie ?', 'La vodka', F),
    b('Quel est l\'ingrédient secret de la sauce worcestershire ?', 'Le vinaigre, la mélasse, l\'anchois...', D),
    b('Quel champignon est utilisé dans la cuisine japonaise pour faire le dashi ?', 'Le kombu et les flocons de bonite', D),
    q('Quel est le plat national de la Hongrie ?', 'Le goulash', M, ['Le strudel', 'Le goulash', 'Le paprikash', 'Le langos']),
    q('Quelle ville française est réputée pour ses quenelles ?', 'Lyon', M, ['Paris', 'Marseille', 'Lyon', 'Bordeaux']),
    v('Le café est originaire d\'Éthiopie.', 'Vrai', M),
    v('Le chocolat provient du cacao, une plante originaire d\'Asie.', 'Faux', M),
    b('Quel est le plat traditionnel de la cuisine grecque à base d\'aubergines ?', 'La moussaka', M),
    b('Quel est le dessert traditionnel turc à base de pâte filo et de miel ?', 'La baklava', M),
    b('Dans quelle ville française se déroule chaque année la Fête des Lumières ?', 'Lyon', M),
    b('Quelle est la boisson nationale de Cuba ?', 'Le rhum', M),
  ].map(o => ({ ...o, categorieId: gastro.id }))

  const extraLittQ = [
    b('Qui a écrit « Les Raisins de la colère » ?', 'John Steinbeck', M),
    b('Qui a écrit « L\'attrape-cœurs » ?', 'J.D. Salinger', M),
    b('Qui est l\'auteur de « La Ferme des animaux » ?', 'George Orwell', M),
    b('Qui a écrit « Le Vieil Homme et la mer » ?', 'Ernest Hemingway', M),
    b('Qui a écrit « Orgueil et Préjugés » ?', 'Jane Austen', M),
    b('Qui a écrit « Les Trois Mousquetaires » ?', 'Alexandre Dumas', F),
    b('Qui a écrit « La Métamorphose » ?', 'Franz Kafka', M),
    b('Qui a écrit « Dracula » ?', 'Bram Stoker', M),
    b('Quel poète anglais est connu pour « Ode to a Nightingale » ?', 'John Keats', D),
    b('Qui a écrit « Les Aventures de Tom Sawyer » ?', 'Mark Twain', M),
    b('Quel auteur belge est connu pour ses romans policiers avec le personnage de Maigret ?', 'Georges Simenon', M),
    b('Qui a écrit « Le Horla » (nouvelle fantastique) ?', 'Guy de Maupassant', M),
    q('Dans quel roman de Dickens le personnage d\'Ebenezer Scrooge apparaît-il ?', 'Un chant de Noël', M, ['Oliver Twist', 'David Copperfield', 'Un chant de Noël', 'Grandes Espérances']),
    q('Qui a écrit « Anna Karénine » ?', 'Léon Tolstoï', M, ['Dostoïevski', 'Tchekhov', 'Léon Tolstoï', 'Tourgueniev']),
    v('La Saga des Rougon-Macquart d\'Émile Zola compte 20 romans.', 'Vrai', D),
    v('Jules Verne était français.', 'Vrai', F),
    b('Qui a écrit « L\'Île au trésor » ?', 'Robert Louis Stevenson', M),
    b('Quel auteur a écrit « Fahrenheit 451 » ?', 'Ray Bradbury', M),
    b('Qui est l\'auteur de « La Nausée » (roman existentialiste) ?', 'Jean-Paul Sartre', M),
    b('Quel poète français est connu pour ses Sonnets ?', 'Ronsard, Du Bellay...', D),
  ].map(o => ({ ...o, categorieId: litt.id }))

  const extraArtQ = [
    b('Quel architecte est connu pour avoir conçu la Sagrada Família ?', 'Antoni Gaudí', M),
    b('Quel artiste est à l\'origine du mouvement pop art américain ?', 'Andy Warhol', M),
    b('Dans quel pays se trouve le Taj Mahal ?', 'L\'Inde', F),
    b('Quel photographe a immortalisé « La Photo du siècle » du baiser à New York (1945) ?', 'Alfred Eisenstaedt', D),
    b('Quel est le style de Frida Kahlo ?', 'Le surréalisme / l\'art mexicain', M),
    b('Quel peintre espagnol est connu pour ses peintures noires ?', 'Francisco de Goya', D),
    b('Quel artiste a créé le concept de « happening » en art ?', 'Allan Kaprow', D),
    b('Dans quelle ville est situé le musée Thyssen-Bornemisza ?', 'Madrid', D),
    b('Quel est le style architectural de la Villa Savoye (Le Corbusier) ?', 'Le modernisme / fonctionnalisme', D),
    q('Qui a peint « Les Ménines » ?', 'Velázquez', M, ['Goya', 'El Greco', 'Velázquez', 'Murillo']),
    q('Dans quel pays se trouve le musée de l\'Ermitage ?', 'En Russie (Saint-Pétersbourg)', M, ['France', 'Allemagne', 'En Russie', 'Italie']),
    v('Le Bauhaus était une école d\'art allemande fondée en 1919.', 'Vrai', D),
    v('Léonard de Vinci était gaucher.', 'Vrai', D),
    b('Quel artiste a peint « La Liberté guidant le peuple » ?', 'Eugène Delacroix', M),
    b('Quel est le style caractéristique de Salvador Dalí ?', 'Le surréalisme', M),
    b('Quel architecte est connu pour la Maison de verre à Paris ?', 'Pierre Chareau', D),
  ].map(o => ({ ...o, categorieId: art.id }))

  const extraTechQ = [
    b('Quel est le nom du premier robot envoyé sur Mars par la NASA ?', 'Sojourner (1997)', D),
    b('Qui a fondé Amazon ?', 'Jeff Bezos', F),
    b('Quel est le langage de programmation utilisé pour créer des applications Android ?', 'Java ou Kotlin', M),
    b('Que signifie « USB » ?', 'Universal Serial Bus', M),
    b('Qui a inventé le téléphone portable ?', 'Martin Cooper (Motorola, 1973)', D),
    b('Quel est le nom du protocole de sécurité des connexions web (cadenas) ?', 'HTTPS / SSL / TLS', M),
    b('Quelle entreprise a développé le processeur Ryzen ?', 'AMD', M),
    b('Quel langage de programmation est créé pour les statistiques ?', 'R', D),
    b('Qu\'est-ce que le « machine learning » ?', 'L\'apprentissage automatique des machines à partir de données', M),
    b('Quelle est la résolution d\'un écran 4K ?', '3840 × 2160 pixels', M),
    q('Quel est le système de fichiers utilisé par défaut sur Windows ?', 'NTFS', M, ['FAT32', 'exFAT', 'NTFS', 'ext4']),
    q('Quelle entreprise a développé le jeu Minecraft ?', 'Mojang (racheté par Microsoft)', M, ['Nintendo', 'Mojang', 'Valve', 'EA Games']),
    v('Le premier e-mail a été envoyé en 1971.', 'Vrai', D),
    v('Python est un langage compilé.', 'Faux', M),
    b('Quel est le nom de l\'algorithme de recherche de Google ?', 'PageRank', D),
    b('Quel est le jeu vidéo le plus joué en ligne au monde (2023) ?', 'League of Legends ou Roblox', M),
    b('Quel est l\'écran le plus fin jamais produit (technologie OLED) ?', 'Moins d\'1 mm', D),
    b('Que signifie « API » en informatique ?', 'Application Programming Interface', M),
  ].map(o => ({ ...o, categorieId: tech.id }))

  const extraNatureQ = [
    b('Quel est le plus grand félin du monde ?', 'Le tigre de l\'Amour (Sibérie)', M),
    b('Combien d\'espèces de tortues marines existent ?', '7', D),
    b('Quel animal est à l\'origine du terme « kangourou » ?', 'Le kangourou (du mot aborigène)', F),
    b('Quelle fleur est connue pour ses propriétés médicinales dans le traitement du paludisme ?', 'L\'artémisia', D),
    b('Quel arbre produit les marrons d\'Inde ?', 'Le marronnier', F),
    b('Quel est le nom du processus par lequel une larve devient papillon ?', 'La métamorphose', F),
    b('Quel est le seul oiseau capable de voler à reculons ?', 'Le colibri', M),
    b('Dans quel pays vit le panda géant à l\'état sauvage ?', 'En Chine', F),
    b('Quel est l\'animal avec la plus grande mémoire ?', 'L\'éléphant (ou les dauphins, selon les critères)', M),
    b('Quel est le nom du plus grand requin qui ait jamais existé ?', 'Le mégalodon', M),
    q('Quel est le seul continent où vivent les gorilles sauvages ?', 'L\'Afrique', F, ['L\'Asie', 'L\'Afrique', 'L\'Amérique du Sud', 'L\'Océanie']),
    q('Combien d\'espèces de lions existent à l\'état sauvage ?', '2 (africain et asiatique)', D, ['1', '2', '3', '5']),
    v('Le requin baleine est le plus grand poisson du monde.', 'Vrai', M),
    v('Les dauphins ont des noms individuels dans leur groupe.', 'Vrai', D),
    b('Quel est le champignon le plus dangereux ?', 'L\'amanite phalloïde', M),
    b('Quel est l\'animal symbole des États-Unis ?', 'L\'aigle chauve', F),
    b('Quelle plante est surnommée « l\'aloe vera » en raison de ses propriétés ?', 'L\'aloès (Aloe vera)', F),
    b('Quel est l\'arbre qui produit les olives ?', 'L\'olivier', F),
  ].map(o => ({ ...o, categorieId: nature.id }))

  const extraCultQ = [
    b('Quel est le premier pays à avoir utilisé l\'euro ?', '12 pays européens simultanément (2002)', M),
    b('Combien y a-t-il de membres permanents au Conseil de sécurité de l\'ONU ?', '5', M),
    b('Quelle est la monnaie du Japon ?', 'Le yen', F),
    b('Quel est le nom du chef de l\'État en France ?', 'Le Président de la République', F),
    b('Combien d\'années dure le mandat présidentiel en France ?', '5 ans', F),
    b('Quel est le nom de la haute assemblée législative en France ?', 'Le Sénat', M),
    b('Dans la mythologie, qui est la muse de l\'histoire ?', 'Clio', D),
    b('Quel est le symbole chimique de l\'argent ?', 'Ag', M),
    b('Combien d\'éléments composent le tableau périodique (actuellement) ?', '118', D),
    b('Quelle est la distance d\'un marathon ?', '42,195 km', M),
    b('Quel est le nombre de cartes dans un jeu de 54 cartes ?', '54 (52 + 2 jokers)', F),
    b('Quel est le Sphinx le plus connu, situé en Égypte ?', 'Le Grand Sphinx de Gizeh', F),
    b('Dans la mythologie grecque, qui était le messager des dieux ?', 'Hermès', M),
    b('Quel est le premier pays à avoir envoyé un homme dans l\'espace ?', 'L\'URSS (Youri Gagarine, 1961)', M),
    b('Quelle est la monnaie des États-Unis ?', 'Le dollar', F),
    q('Quel est le plus grand pays francophone du monde (superficie) ?', 'La République démocratique du Congo', M, ['La France', 'Le Canada', 'La République démocratique du Congo', 'L\'Algérie']),
    q('Combien de pays utilisent l\'euro comme monnaie officielle ?', '20', M, ['17', '18', '19', '20']),
    v('La Déclaration des droits de l\'homme date de 1789.', 'Vrai', F),
    v('Le symbole de la paix (colombe) vient d\'un tableau de Picasso.', 'Vrai', D),
    b('Quel est le prénom de l\'actuel pape (2024) ?', 'François (Jorge Mario Bergoglio)', M),
    b('Quel est le cri de guerre des légions romaines ?', 'Vive l\'Imperator / Ave Caesar', D),
    b('Quel est le proverbe latin « Cogito ergo sum » (en français) ?', '« Je pense, donc je suis »', M),
    b('Quel est le premier chiffre de Pi (3,14...) ?', '3', F),
    b('Quel est le nombre d\'Avogadro (ordre de grandeur) ?', '6,022 × 10²³', D),
  ].map(o => ({ ...o, categorieId: cult.id }))

  const allQuestions = [
    ...geoQ, ...histQ, ...sciQ, ...cineQ, ...musQ,
    ...sportQ, ...gastroQ, ...littQ, ...artQ, ...techQ,
    ...natureQ, ...cultQ,
    ...extraGeoQ, ...extraHistQ, ...extraSciQ, ...extraCineQ, ...extraMusQ,
    ...extraSportQ, ...extraGastroQ, ...extraLittQ, ...extraArtQ, ...extraTechQ,
    ...extraNatureQ, ...extraCultQ,
    // === 7 questions supplémentaires pour atteindre 1 000 ===
    ...[
      b('Quel est le nom de la cérémonie japonaise du thé ?', 'Chanoyu (ou Chadō)', M),
      b('Qui a inventé le téléscope ?', 'Hans Lippershey (ou Galilée pour son perfectionnement)', D),
      b('Quelle est la formule de la circonférence d\'un cercle ?', '2πr', M),
      b('Quel est le plus grand amphithéâtre de la Rome antique ?', 'Le Colisée', F),
      b('Quel est le nom de l\'art japonais du pliage de papier ?', 'L\'origami', F),
      v('Le Parlement européen siège à Strasbourg et à Bruxelles.', 'Vrai', M),
      b('Quelle est la couleur du drapeau de la Croix-Rouge ?', 'Blanc avec une croix rouge', F),
    ].map(o => ({ ...o, categorieId: cult.id })),
  ]

  return allQuestions
}
